const WORKBOARD_DUMMY_DATA = [
  {
    id: 1,
    boardId: "BRD-000001",
    name: "Exam Schedule Planning",
    code: "ESP",
    coverImage: "https://picsum.photos/seed/ExamSchedulePlanning/400/200",
    adminUser: { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    members: [
      { name: "Ahmed Khan",    avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5" },
    ],
    category: "Planning",
    description:
      "Comprehensive planning board for the mid-term and final examination schedules. Covers date allocation, hall assignments, invigilator duties, and result processing timelines. All academic staff are involved in the planning process.",
    status: "Active",
    isStarred: true,
    taskCount: 24,
    completedTasks: 18,
    createdAt: "2025-01-10",
    updatedAt: "2025-02-20",
  },
  {
    id: 2,
    boardId: "BRD-000002",
    name: "Annual Day Preparation",
    code: "ADP",
    coverImage: "https://picsum.photos/seed/AnnualDayPreparation/400/200",
    adminUser: { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    members: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5" },
      { name: "Hina Khan",     avatar: "https://i.pravatar.cc/150?img=17" },
    ],
    category: "Kanban",
    description:
      "Full event planning board for the school's annual day celebration. Tracks stage setup, performances, guest invitations, decorations, and catering arrangements. Assigned to the events committee with weekly reviews.",
    status: "Active",
    isStarred: false,
    taskCount: 30,
    completedTasks: 12,
    createdAt: "2025-01-15",
    updatedAt: "2025-02-18",
  },
  {
    id: 3,
    boardId: "BRD-000003",
    name: "Curriculum Development",
    code: "CDV",
    coverImage: "https://picsum.photos/seed/CurriculumDevelopment/400/200",
    adminUser: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    members: [
      { name: "Ahmed Khan",  avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    ],
    category: "Scrum",
    description:
      "Board for tracking updates and revisions to the school curriculum across all grade levels. Includes mapping new learning outcomes, textbook updates, and alignment with national education standards. Reviewed quarterly by the academic board.",
    status: "Completed",
    isStarred: true,
    taskCount: 20,
    completedTasks: 20,
    createdAt: "2024-12-01",
    updatedAt: "2025-01-21",
  },
  {
    id: 4,
    boardId: "BRD-000004",
    name: "Student Admissions 2025",
    code: "SA25",
    coverImage: "https://picsum.photos/seed/StudentAdmissions2025/400/200",
    adminUser: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    members: [
      { name: "Fatima Malik",     avatar: "https://i.pravatar.cc/150?img=2" },
      { name: "Hassan Raza",      avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Omar Farooq",      avatar: "https://i.pravatar.cc/150?img=14" },
    ],
    category: "Sprint",
    description:
      "Tracks the full admissions cycle for the 2025 intake, including application review, entrance test scheduling, interviews, merit list publication, and fee collection. All admission officers are assigned tasks on this board.",
    status: "Active",
    isStarred: false,
    taskCount: 28,
    completedTasks: 10,
    createdAt: "2025-02-01",
    updatedAt: "2025-02-28",
  },
  {
    id: 5,
    boardId: "BRD-000005",
    name: "Staff Training Program",
    code: "STP",
    coverImage: "https://picsum.photos/seed/StaffTrainingProgram/400/200",
    adminUser: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    members: [
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Omar Farooq",     avatar: "https://i.pravatar.cc/150?img=14" },
    ],
    category: "To-Do",
    description:
      "Professional development and training board for teaching and administrative staff. Covers workshop scheduling, online course enrollments, certification tracking, and feedback collection. Managed by the HR department.",
    status: "On Hold",
    isStarred: false,
    taskCount: 15,
    completedTasks: 6,
    createdAt: "2025-01-20",
    updatedAt: "2025-02-10",
  },
  {
    id: 6,
    boardId: "BRD-000006",
    name: "Library Management",
    code: "LMB",
    coverImage: "https://picsum.photos/seed/LibraryManagement/400/200",
    adminUser: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    members: [
      { name: "Bilal Ahmad",  avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Hina Khan",    avatar: "https://i.pravatar.cc/150?img=17" },
      { name: "Sana Tariq",   avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    category: "Kanban",
    description:
      "Board for managing library operations including cataloging new books, tracking issued copies, overdue returns, and digital system integration. Handles procurement requests and book donations as well.",
    status: "Active",
    isStarred: true,
    taskCount: 18,
    completedTasks: 14,
    createdAt: "2025-02-10",
    updatedAt: "2025-02-25",
  },
  {
    id: 7,
    boardId: "BRD-000007",
    name: "Sports Event Planning",
    code: "SEP",
    coverImage: "https://picsum.photos/seed/SportsEventPlanning/400/200",
    adminUser: { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    members: [
      { name: "Zain Ul Abidin", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Maria Sheikh",   avatar: "https://i.pravatar.cc/150?img=13" },
    ],
    category: "Sprint",
    description:
      "Event planning board for inter-house and inter-school sports competitions. Manages fixture scheduling, venue booking, referee assignments, equipment procurement, and award ceremonies. Coordinated with the PE department.",
    status: "Archived",
    isStarred: false,
    taskCount: 22,
    completedTasks: 22,
    createdAt: "2024-11-01",
    updatedAt: "2024-12-15",
  },
  {
    id: 8,
    boardId: "BRD-000008",
    name: "Parent Meeting Schedule",
    code: "PMS",
    coverImage: "https://picsum.photos/seed/ParentMeetingSchedule/400/200",
    adminUser: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    members: [
      { name: "Ahmed Khan",  avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Bilal Ahmad", avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Usman Ali",   avatar: "https://i.pravatar.cc/150?img=18" },
    ],
    category: "Planning",
    description:
      "Organizes parent-teacher meetings for quarterly reporting sessions. Tracks appointment slots, communication with parents, report card distribution, and follow-up tasks. Ensures all parents receive timely invitations.",
    status: "Active",
    isStarred: true,
    taskCount: 12,
    completedTasks: 9,
    createdAt: "2025-01-25",
    updatedAt: "2025-02-22",
  },
  {
    id: 9,
    boardId: "BRD-000009",
    name: "School Budget Planning",
    code: "SBP",
    coverImage: "https://picsum.photos/seed/SchoolBudgetPlanning/400/200",
    adminUser: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    members: [
      { name: "Hina Khan",    avatar: "https://i.pravatar.cc/150?img=17" },
      { name: "Sana Tariq",   avatar: "https://i.pravatar.cc/150?img=19" },
      { name: "Maria Sheikh", avatar: "https://i.pravatar.cc/150?img=13" },
    ],
    category: "Scrum",
    description:
      "Annual budget planning board covering departmental allocations, procurement approvals, infrastructure spending, and contingency reserves. Reviewed monthly by finance committee and school principal.",
    status: "On Hold",
    isStarred: false,
    taskCount: 16,
    completedTasks: 5,
    createdAt: "2025-02-18",
    updatedAt: "2025-02-28",
  },
  {
    id: 10,
    boardId: "BRD-000010",
    name: "Infrastructure Upgrade",
    code: "IFU",
    coverImage: "https://picsum.photos/seed/InfrastructureUpgrade/400/200",
    adminUser: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    members: [
      { name: "Hassan Raza",  avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    ],
    category: "Retrospective",
    description:
      "Tracks school infrastructure improvement projects including electrical upgrades, CCTV installation, furniture replacement, and classroom refurbishment. Budget approved; vendor selection in progress.",
    status: "On Hold",
    isStarred: false,
    taskCount: 20,
    completedTasks: 7,
    createdAt: "2025-02-05",
    updatedAt: "2025-02-20",
  },
  {
    id: 11,
    boardId: "BRD-000011",
    name: "Digital Learning Initiative",
    code: "DLI",
    coverImage: "https://picsum.photos/seed/DigitalLearningInitiative/400/200",
    adminUser: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    members: [
      { name: "Usman Ali",   avatar: "https://i.pravatar.cc/150?img=18" },
      { name: "Bilal Ahmad", avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Ahmed Khan",  avatar: "https://i.pravatar.cc/150?img=1" },
    ],
    category: "Scrum",
    description:
      "Board for rolling out e-learning platforms, tablet distribution, and online content creation for all grades. Includes teacher training on LMS tools, student account setup, and digital assessment integration.",
    status: "Active",
    isStarred: true,
    taskCount: 25,
    completedTasks: 17,
    createdAt: "2025-01-15",
    updatedAt: "2025-02-25",
  },
  {
    id: 12,
    boardId: "BRD-000012",
    name: "Extracurricular Activities",
    code: "ECA",
    coverImage: "https://picsum.photos/seed/ExtracurricularActivities/400/200",
    adminUser: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    members: [
      { name: "Ahmed Khan",    avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2" },
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    ],
    category: "Kanban",
    description:
      "Manages all extracurricular clubs and activities including registration, timetabling, teacher coordinator assignments, and inter-school competition participation. Updated at the start of each academic term.",
    status: "Completed",
    isStarred: false,
    taskCount: 18,
    completedTasks: 18,
    createdAt: "2024-08-15",
    updatedAt: "2025-01-02",
  },
  {
    id: 13,
    boardId: "BRD-000013",
    name: "Student Welfare Board",
    code: "SWB",
    coverImage: "https://picsum.photos/seed/StudentWelfareBoard/400/200",
    adminUser: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    members: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    category: "To-Do",
    description:
      "Tracks student welfare initiatives including counseling sessions, scholarship applications, meal programs, and mental health awareness campaigns. Reviewed monthly by the school welfare committee.",
    status: "Active",
    isStarred: false,
    taskCount: 14,
    completedTasks: 8,
    createdAt: "2025-02-22",
    updatedAt: "2025-02-28",
  },
  {
    id: 14,
    boardId: "BRD-000014",
    name: "Academic Calendar 2025",
    code: "AC25",
    coverImage: "https://picsum.photos/seed/AcademicCalendar2025/400/200",
    adminUser: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    members: [
      { name: "Bilal Ahmad", avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Hina Khan",   avatar: "https://i.pravatar.cc/150?img=17" },
      { name: "Sana Tariq",  avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    category: "Planning",
    description:
      "Annual academic calendar planning board covering term dates, holidays, examination windows, and event milestones. Coordinates across all departments to avoid scheduling conflicts throughout the year.",
    status: "Completed",
    isStarred: true,
    taskCount: 10,
    completedTasks: 10,
    createdAt: "2024-12-20",
    updatedAt: "2025-01-05",
  },
  {
    id: 15,
    boardId: "BRD-000015",
    name: "Safety & Security Plan",
    code: "SSP",
    coverImage: "https://picsum.photos/seed/SafetySecurityPlan/400/200",
    adminUser: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    members: [
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Omar Farooq",     avatar: "https://i.pravatar.cc/150?img=14" },
      { name: "Zain Ul Abidin",  avatar: "https://i.pravatar.cc/150?img=12" },
    ],
    category: "Retrospective",
    description:
      "Board dedicated to school safety protocols, fire drill scheduling, CCTV monitoring, visitor management system, and emergency response planning. Updated after each quarterly safety audit.",
    status: "Active",
    isStarred: false,
    taskCount: 5,
    completedTasks: 3,
    createdAt: "2025-02-01",
    updatedAt: "2025-02-24",
  },
  {
    id: 16,
    boardId: "BRD-000016",
    name: "Community Outreach",
    code: "COM",
    coverImage: "https://picsum.photos/seed/CommunityOutreach/400/200",
    adminUser: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    members: [
      { name: "Ahmed Khan",  avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    ],
    category: "Sprint",
    description:
      "Manages community engagement programs including awareness drives, charity events, neighborhood clean-up campaigns, and partnerships with local organizations. Reflects the school's commitment to social responsibility.",
    status: "Archived",
    isStarred: false,
    taskCount: 8,
    completedTasks: 8,
    createdAt: "2025-02-25",
    updatedAt: "2025-02-28",
  },
];

export default WORKBOARD_DUMMY_DATA;
