const GROUPS_DUMMY_DATA = [
  {
    id: 1,
    groupId: "GRP-000001",
    name: "Grade 10 Mathematics",
    code: "G10M",
    coverImage: "https://picsum.photos/seed/Grade10Mathematics/400/200",
    adminUser: { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    members: [
      { name: "Ali Hassan",       avatar: "https://i.pravatar.cc/150?img=10" },
      { name: "Sara Ahmed",       avatar: "https://i.pravatar.cc/150?img=11" },
      { name: "Zain Ul Abidin",   avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Maria Sheikh",     avatar: "https://i.pravatar.cc/150?img=13" },
      { name: "Omar Farooq",      avatar: "https://i.pravatar.cc/150?img=14" },
    ],
    category: "Class Group",
    description:
      "Official class group for Grade 10 Mathematics students. Share assignments, notes, and exam schedules. Teacher posts daily updates and homework reminders here.",
    type: "Private",
    isStarred: true,
    memberCount: 38,
    createdAt: "2025-01-05",
    updatedAt: "2025-02-25",
  },
  {
    id: 2,
    groupId: "GRP-000002",
    name: "Science Club",
    code: "SCI",
    coverImage: "https://picsum.photos/seed/ScienceClub/400/200",
    adminUser: { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    members: [
      { name: "Bilal Ahmad",     avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Hina Khan",       avatar: "https://i.pravatar.cc/150?img=17" },
      { name: "Usman Ali",       avatar: "https://i.pravatar.cc/150?img=18" },
      { name: "Sana Tariq",      avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    category: "Club",
    description:
      "Science enthusiasts unite! We conduct weekly experiments, discuss latest discoveries, and prepare for science competitions. All students interested in biology, chemistry, and physics are welcome.",
    type: "Public",
    isStarred: false,
    memberCount: 24,
    createdAt: "2025-01-10",
    updatedAt: "2025-02-20",
  },
  {
    id: 3,
    groupId: "GRP-000003",
    name: "Basketball Team",
    code: "BSKT",
    coverImage: "https://picsum.photos/seed/BasketballTeam/400/200",
    adminUser: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    members: [
      { name: "Ali Hassan",   avatar: "https://i.pravatar.cc/150?img=10" },
      { name: "Bilal Ahmad",  avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Usman Ali",    avatar: "https://i.pravatar.cc/150?img=18" },
      { name: "Omar Farooq",  avatar: "https://i.pravatar.cc/150?img=14" },
    ],
    category: "Sports",
    description:
      "School basketball team for inter-school competitions. Practice sessions every Tuesday and Thursday. Tryouts are open to Grade 8 to 11 students at the start of each semester.",
    type: "Private",
    isStarred: true,
    memberCount: 15,
    createdAt: "2025-01-08",
    updatedAt: "2025-02-22",
  },
  {
    id: 4,
    groupId: "GRP-000004",
    name: "Drama Club",
    code: "DRAM",
    coverImage: "https://picsum.photos/seed/DramaClub/400/200",
    adminUser: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    members: [
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Hina Khan",       avatar: "https://i.pravatar.cc/150?img=17" },
      { name: "Sana Tariq",      avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    category: "Club",
    description:
      "School drama and performing arts club. We rehearse plays, skits, and annual productions. Students develop acting, scriptwriting, and stage management skills throughout the year.",
    type: "Public",
    isStarred: false,
    memberCount: 18,
    createdAt: "2025-01-15",
    updatedAt: "2025-02-18",
  },
  {
    id: 5,
    groupId: "GRP-000005",
    name: "Student Council",
    code: "SC",
    coverImage: "https://picsum.photos/seed/StudentCouncil/400/200",
    adminUser: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    members: [
      { name: "Bilal Ahmad",     avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Hina Khan",       avatar: "https://i.pravatar.cc/150?img=17" },
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Omar Farooq",     avatar: "https://i.pravatar.cc/150?img=14" },
    ],
    category: "Club",
    description:
      "Elected student representatives coordinating school activities and events. Responsible for planning cultural days, addressing student concerns, and liaising with school administration.",
    type: "Private",
    isStarred: true,
    memberCount: 12,
    createdAt: "2025-01-20",
    updatedAt: "2025-02-26",
  },
  {
    id: 6,
    groupId: "GRP-000006",
    name: "Chess Club",
    code: "CHES",
    coverImage: "https://picsum.photos/seed/ChessClub/400/200",
    adminUser: { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    members: [
      { name: "Zain Ul Abidin", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Maria Sheikh",   avatar: "https://i.pravatar.cc/150?img=13" },
      { name: "Ali Hassan",     avatar: "https://i.pravatar.cc/150?img=10" },
    ],
    category: "Club",
    description:
      "Chess enthusiasts meet every Wednesday after school. We organize internal tournaments and participate in district-level chess competitions. All skill levels are welcome to join.",
    type: "Public",
    isStarred: false,
    memberCount: 20,
    createdAt: "2025-01-12",
    updatedAt: "2025-02-15",
  },
  {
    id: 7,
    groupId: "GRP-000007",
    name: "Art & Craft Club",
    code: "ART",
    coverImage: "https://picsum.photos/seed/ArtCraftClub/400/200",
    adminUser: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    members: [
      { name: "Sara Ahmed",      avatar: "https://i.pravatar.cc/150?img=11" },
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Maria Sheikh",    avatar: "https://i.pravatar.cc/150?img=13" },
      { name: "Sana Tariq",      avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    category: "Club",
    description:
      "A creative space for students to explore painting, sketching, sculpture, and digital art. We exhibit student work annually and participate in regional art competitions throughout the year.",
    type: "Public",
    isStarred: false,
    memberCount: 22,
    createdAt: "2025-01-18",
    updatedAt: "2025-02-20",
  },
  {
    id: 8,
    groupId: "GRP-000008",
    name: "Debate Society",
    code: "DEB",
    coverImage: "https://picsum.photos/seed/DebateSociety/400/200",
    adminUser: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    members: [
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Omar Farooq",     avatar: "https://i.pravatar.cc/150?img=14" },
      { name: "Zain Ul Abidin",  avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Bilal Ahmad",     avatar: "https://i.pravatar.cc/150?img=16" },
    ],
    category: "Study Group",
    description:
      "School debate society focusing on public speaking, logical argumentation, and current affairs. Weekly debate sessions with rotating topics help students build confidence and critical thinking.",
    type: "Public",
    isStarred: true,
    memberCount: 16,
    createdAt: "2025-01-22",
    updatedAt: "2025-02-24",
  },
  {
    id: 9,
    groupId: "GRP-000009",
    name: "Environmental Club",
    code: "ENV",
    coverImage: "https://picsum.photos/seed/EnvironmentalClub/400/200",
    adminUser: { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    members: [
      { name: "Zain Ul Abidin", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Maria Sheikh",   avatar: "https://i.pravatar.cc/150?img=13" },
      { name: "Hina Khan",      avatar: "https://i.pravatar.cc/150?img=17" },
    ],
    category: "Club",
    description:
      "Promoting environmental awareness and sustainability practices within the school community. Activities include tree planting, recycling drives, and conducting eco-awareness workshops for junior students.",
    type: "Public",
    isStarred: false,
    memberCount: 28,
    createdAt: "2025-01-25",
    updatedAt: "2025-02-22",
  },
  {
    id: 10,
    groupId: "GRP-000010",
    name: "Music Band",
    code: "BAND",
    coverImage: "https://picsum.photos/seed/MusicBand/400/200",
    adminUser: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    members: [
      { name: "Bilal Ahmad",  avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Sana Tariq",   avatar: "https://i.pravatar.cc/150?img=19" },
      { name: "Ali Hassan",   avatar: "https://i.pravatar.cc/150?img=10" },
      { name: "Usman Ali",    avatar: "https://i.pravatar.cc/150?img=18" },
    ],
    category: "Club",
    description:
      "School music band covering classical, pop, and traditional instruments. We perform at school events, cultural festivals, and participate in inter-school music competitions each year.",
    type: "Private",
    isStarred: false,
    memberCount: 14,
    createdAt: "2025-01-28",
    updatedAt: "2025-02-18",
  },
  {
    id: 11,
    groupId: "GRP-000011",
    name: "Photography Club",
    code: "PHOT",
    coverImage: "https://picsum.photos/seed/PhotographyClub/400/200",
    adminUser: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    members: [
      { name: "Sara Ahmed",   avatar: "https://i.pravatar.cc/150?img=11" },
      { name: "Omar Farooq",  avatar: "https://i.pravatar.cc/150?img=14" },
      { name: "Maria Sheikh", avatar: "https://i.pravatar.cc/150?img=13" },
    ],
    category: "Club",
    description:
      "Learn photography fundamentals, photo editing, and visual storytelling. Members document school events and produce a yearly photo book. Weekend field trips for nature and street photography.",
    type: "Public",
    isStarred: true,
    memberCount: 19,
    createdAt: "2025-02-01",
    updatedAt: "2025-02-25",
  },
  {
    id: 12,
    groupId: "GRP-000012",
    name: "Coding Club",
    code: "CODE",
    coverImage: "https://picsum.photos/seed/CodingClub/400/200",
    adminUser: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    members: [
      { name: "Usman Ali",      avatar: "https://i.pravatar.cc/150?img=18" },
      { name: "Bilal Ahmad",    avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Zain Ul Abidin", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Ali Hassan",     avatar: "https://i.pravatar.cc/150?img=10" },
    ],
    category: "Study Group",
    description:
      "Programming and software development club for tech-savvy students. We cover web development, Python, and app design. Members participate in hackathons and coding competitions.",
    type: "Public",
    isStarred: false,
    memberCount: 21,
    createdAt: "2025-02-03",
    updatedAt: "2025-02-27",
  },
  {
    id: 13,
    groupId: "GRP-000013",
    name: "Swimming Team",
    code: "SWIM",
    coverImage: "https://picsum.photos/seed/SwimmingTeam/400/200",
    adminUser: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    members: [
      { name: "Ali Hassan",   avatar: "https://i.pravatar.cc/150?img=10" },
      { name: "Usman Ali",    avatar: "https://i.pravatar.cc/150?img=18" },
      { name: "Omar Farooq",  avatar: "https://i.pravatar.cc/150?img=14" },
    ],
    category: "Sports",
    description:
      "Competitive swimming team for school-level and district-level swimming competitions. Training sessions run Monday, Wednesday, and Friday mornings. Open tryouts at the beginning of each term.",
    type: "Private",
    isStarred: false,
    memberCount: 12,
    createdAt: "2025-02-05",
    updatedAt: "2025-02-20",
  },
  {
    id: 14,
    groupId: "GRP-000014",
    name: "Library Club",
    code: "LIB",
    coverImage: "https://picsum.photos/seed/LibraryClub/400/200",
    adminUser: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    members: [
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Sara Ahmed",      avatar: "https://i.pravatar.cc/150?img=11" },
      { name: "Maria Sheikh",    avatar: "https://i.pravatar.cc/150?img=13" },
    ],
    category: "Study Group",
    description:
      "Book lovers and reading enthusiasts gathering to discuss literature, share recommendations, and manage the school library. Monthly reading challenges and author discussions are organized regularly.",
    type: "Public",
    isStarred: false,
    memberCount: 17,
    createdAt: "2025-02-08",
    updatedAt: "2025-02-23",
  },
  {
    id: 15,
    groupId: "GRP-000015",
    name: "Parent Teacher Group",
    code: "PTG",
    coverImage: "https://picsum.photos/seed/ParentTeacherGroup/400/200",
    adminUser: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    members: [
      { name: "Ahmed Khan",    avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2" },
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    ],
    category: "Class Group",
    description:
      "Official communication channel between parents and teachers. Monthly meeting schedules, progress reports, and important school announcements shared here. Parents can raise concerns directly.",
    type: "Private",
    isStarred: true,
    memberCount: 45,
    createdAt: "2025-01-02",
    updatedAt: "2025-02-28",
  },
  {
    id: 16,
    groupId: "GRP-000016",
    name: "Alumni Network",
    code: "ALUM",
    coverImage: "https://picsum.photos/seed/AlumniNetwork/400/200",
    adminUser: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    members: [
      { name: "Ahmed Khan",  avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
      { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    category: "Study Group",
    description:
      "Connect with school graduates across all batches. Share career opportunities, mentorship, and stay updated on school news. Annual alumni reunion planning and networking events organized here.",
    type: "Public",
    isStarred: false,
    memberCount: 120,
    createdAt: "2024-12-01",
    updatedAt: "2025-02-25",
  },
];

export default GROUPS_DUMMY_DATA;
