const teachers = [
  {
    id: "T849127",
    name: "Teresa",
    classLabel: "III A",
    phone: "+1 82392 37359",
    email: "teresa@example.com",
    avatar: "https://i.pravatar.cc/100?img=32",
    subject: "Physics",
    department: "Science",
    status: "Active",
    joinedOn: "14 May 2017",
  },
  {
    id: "T849126",
    name: "Daniel",
    classLabel: "II (A)",
    phone: "+1 56752 86742",
    email: "daniel@example.com",
    avatar: "https://i.pravatar.cc/100?img=10",
    subject: "Computer",
    department: "IT",
    status: "Active",
    joinedOn: "22 Nov 2016",
  },
  {
    id: "T849125",
    name: "Hellana",
    classLabel: "VI (A)",
    phone: "+1 23566 52683",
    email: "hellana@example.com",
    avatar: "https://i.pravatar.cc/100?img=14",
    subject: "English",
    department: "Languages",
    status: "Active",
    joinedOn: "15 Feb 2019",
  },
  {
    id: "T849124",
    name: "Erickson",
    classLabel: "VI (B)",
    phone: "+1 14259 85573",
    email: "erickson@example.com",
    avatar: "https://i.pravatar.cc/100?img=50",
    subject: "Spanish",
    department: "Languages",
    status: "Active",
    joinedOn: "11 Sep 2020",
  },
  {
    id: "T849123",
    name: "Sophia",
    classLabel: "IV A",
    phone: "+1 44521 99873",
    email: "sophia@example.com",
    avatar: "https://i.pravatar.cc/100?img=5",
    subject: "Mathematics",
    department: "Science",
    status: "Active",
    joinedOn: "03 Jan 2018",
  },
  {
    id: "T849122",
    name: "James",
    classLabel: "V A",
    phone: "+1 77521 44321",
    email: "james@example.com",
    avatar: "https://i.pravatar.cc/100?img=12",
    subject: "Chemistry",
    department: "Science",
    status: "Inactive",
    joinedOn: "19 Aug 2015",
  },
  {
    id: "T849121",
    name: "Olivia",
    classLabel: "I A",
    phone: "+1 66521 77821",
    email: "olivia@example.com",
    avatar: "https://i.pravatar.cc/100?img=21",
    subject: "Arts",
    department: "Humanities",
    status: "Active",
    joinedOn: "10 Mar 2021",
  },
  {
    id: "T849120",
    name: "William",
    classLabel: "VII A",
    phone: "+1 90876 55432",
    email: "william@example.com",
    avatar: "https://i.pravatar.cc/100?img=41",
    subject: "History",
    department: "Humanities",
    status: "Active",
    joinedOn: "07 Jul 2016",
  },
  {
    id: "T849119",
    name: "Ava",
    classLabel: "VIII B",
    phone: "+1 55231 98765",
    email: "ava@example.com",
    avatar: "https://i.pravatar.cc/100?img=18",
    subject: "Geography",
    department: "Humanities",
    status: "Active",
    joinedOn: "28 Apr 2019",
  },
  {
    id: "T849118",
    name: "Noah",
    classLabel: "IX A",
    phone: "+1 31245 66789",
    email: "noah@example.com",
    avatar: "https://i.pravatar.cc/100?img=8",
    subject: "Biology",
    department: "Science",
    status: "Active",
    joinedOn: "13 Dec 2017",
  },
  {
    id: "T849117",
    name: "Emma",
    classLabel: "X A",
    phone: "+1 99887 22134",
    email: "emma@example.com",
    avatar: "https://i.pravatar.cc/100?img=29",
    subject: "Economics",
    department: "Commerce",
    status: "Active",
    joinedOn: "06 Jun 2020",
  },
  {
    id: "T849116",
    name: "Liam",
    classLabel: "XI A",
    phone: "+1 77231 55678",
    email: "liam@example.com",
    avatar: "https://i.pravatar.cc/100?img=35",
    subject: "Accounts",
    department: "Commerce",
    status: "Inactive",
    joinedOn: "25 Oct 2014",
  },
  {
    id: "T849115",
    name: "Mia",
    classLabel: "XII A",
    phone: "+1 88123 77654",
    email: "mia@example.com",
    avatar: "https://i.pravatar.cc/100?img=47",
    subject: "Business Studies",
    department: "Commerce",
    status: "Active",
    joinedOn: "09 Sep 2018",
  },
  {
    id: "T849114",
    name: "Lucas",
    classLabel: "III B",
    phone: "+1 44567 88990",
    email: "lucas@example.com",
    avatar: "https://i.pravatar.cc/100?img=3",
    subject: "Urdu",
    department: "Languages",
    status: "Active",
    joinedOn: "17 Feb 2016",
  },
  {
    id: "T849113",
    name: "Amelia",
    classLabel: "IV B",
    phone: "+1 33445 66778",
    email: "amelia@example.com",
    avatar: "https://i.pravatar.cc/100?img=24",
    subject: "Islamiyat",
    department: "Humanities",
    status: "Active",
    joinedOn: "21 Jan 2022",
  },
  {
    id: "T849112",
    name: "Ethan",
    classLabel: "V B",
    phone: "+1 99876 44556",
    email: "ethan@example.com",
    avatar: "https://i.pravatar.cc/100?img=44",
    subject: "Computer",
    department: "IT",
    status: "Active",
    joinedOn: "02 Aug 2019",
  },
  {
    id: "T849111",
    name: "Charlotte",
    classLabel: "VI C",
    phone: "+1 77889 22119",
    email: "charlotte@example.com",
    avatar: "https://i.pravatar.cc/100?img=16",
    subject: "French",
    department: "Languages",
    status: "Active",
    joinedOn: "11 Nov 2017",
  },
  {
    id: "T849110",
    name: "Alexander",
    classLabel: "VII B",
    phone: "+1 66554 99887",
    email: "alexander@example.com",
    avatar: "https://i.pravatar.cc/100?img=52",
    subject: "Physics",
    department: "Science",
    status: "Active",
    joinedOn: "30 Mar 2015",
  },
  {
    id: "T849109",
    name: "Harper",
    classLabel: "VIII A",
    phone: "+1 22334 55667",
    email: "harper@example.com",
    avatar: "https://i.pravatar.cc/100?img=6",
    subject: "Civics",
    department: "Humanities",
    status: "Active",
    joinedOn: "18 May 2021",
  },
  {
    id: "T849108",
    name: "Benjamin",
    classLabel: "IX B",
    phone: "+1 88990 33445",
    email: "benjamin@example.com",
    avatar: "https://i.pravatar.cc/100?img=27",
    subject: "Statistics",
    department: "Science",
    status: "Inactive",
    joinedOn: "12 Dec 2013",
  },
];

export default teachers;
