const REWARDS_DUMMY_DATA = [
  {
    id: 1,
    rewardId: "RWD-000001",
    recipientName: "Ahmed Khan",
    recipientAvatar: "https://i.pravatar.cc/150?img=1",
    recipientRole: "Mathematics Teacher",
    category: "Excellence Award",
    name: "Best Teacher 2025",
    reason: "Outstanding perform.",
    description:
      "Ahmed Khan has demonstrated exceptional dedication to student success throughout the year. His innovative teaching methods have significantly improved mathematics scores across all grade levels.",
    member: { name: "Dr. Sana Malik", avatar: "https://i.pravatar.cc/150?img=10" },
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "approved",
        comment: "Well deserved! Ahmed has been outstanding.",
      },
    ],
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-01-14",
    updatedAt: "2025-01-14",
  },
  {
    id: 2,
    rewardId: "RWD-000002",
    recipientName: "Sara Ali",
    recipientAvatar: "https://i.pravatar.cc/150?img=2",
    recipientRole: "Grade 9 - A",
    category: "Star Student",
    name: "Top Performer Award",
    reason: "Academic excellence",
    description:
      "Sara Ali achieved the highest GPA in her class for two consecutive semesters. She consistently goes beyond the curriculum and participates actively in all academic competitions.",
    member: { name: "Mrs. Ayesha Noor", avatar: "https://i.pravatar.cc/150?img=11" },
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: "https://i.pravatar.cc/150?img=11",
        response: "approved",
        comment: "Sara is truly an exceptional student.",
      },
      {
        id: 2,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "approved",
        comment: "Approved. Keep up the great work!",
      },
    ],
    status: "Approved",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-01-19",
    updatedAt: "2025-01-19",
  },
  {
    id: 3,
    rewardId: "RWD-000003",
    recipientName: "Muhammad Bilal",
    recipientAvatar: "https://i.pravatar.cc/150?img=3",
    recipientRole: "Science Teacher",
    category: "Innovation Award",
    name: "Science Innovator",
    reason: "Lab modernization",
    description:
      "Muhammad Bilal led a complete overhaul of the school science laboratory, introducing modern equipment and digital tools. His initiative resulted in significantly improved student engagement in practical sessions.",
    member: { name: "Mr. Tariq Rehman", avatar: "https://i.pravatar.cc/150?img=12" },
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "approved",
        comment: "Excellent initiative for the school.",
      },
      {
        id: 2,
        name: "Mr. Tariq Rehman",
        role: "HR Manager",
        avatar: "https://i.pravatar.cc/150?img=12",
        response: "pending",
        comment: "",
      },
    ],
    status: "In Process",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-01-28",
    updatedAt: "2025-01-28",
  },
  {
    id: 4,
    rewardId: "RWD-000004",
    recipientName: "Fatima Sheikh",
    recipientAvatar: "https://i.pravatar.cc/150?img=4",
    recipientRole: "Grade 10 - B",
    category: "Leadership Award",
    name: "Student Leader 2025",
    reason: "Exemplary leadership",
    description:
      "Fatima Sheikh served as the Student Council President and organized multiple school-wide events. Her leadership brought students together and improved overall school morale significantly.",
    member: { name: "Mrs. Ayesha Noor", avatar: "https://i.pravatar.cc/150?img=11" },
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: "https://i.pravatar.cc/150?img=11",
        response: "approved",
        comment: "Fatima has been an exceptional leader.",
      },
    ],
    status: "Approved",
    hasAttachment: true,
    attachmentType: "Image",
    createdAt: "2025-01-21",
    updatedAt: "2025-01-21",
  },
  {
    id: 5,
    rewardId: "RWD-000005",
    recipientName: "Omar Farooq",
    recipientAvatar: "https://i.pravatar.cc/150?img=5",
    recipientRole: "English Teacher",
    category: "Best Performance",
    name: "Best Educator Award",
    reason: "Exam results boost",
    description:
      "Omar Farooq's English classes produced the best board examination results in the school's recent history. His structured teaching approach and extra support sessions made a remarkable difference.",
    member: { name: "Dr. Sana Malik", avatar: "https://i.pravatar.cc/150?img=10" },
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "pending",
        comment: "",
      },
    ],
    status: "Pending",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-02-07",
    updatedAt: "2025-02-07",
  },
  {
    id: 6,
    rewardId: "RWD-000006",
    recipientName: "Ayesha Malik",
    recipientAvatar: "https://i.pravatar.cc/150?img=6",
    recipientRole: "Grade 11 - A",
    category: "Attendance Award",
    name: "Perfect Attendance",
    reason: "Zero absences",
    description:
      "Ayesha Malik maintained a perfect attendance record for the entire academic year without a single absence or late arrival. Her dedication and commitment to her education serves as an inspiration to peers.",
    member: { name: "Mrs. Ayesha Noor", avatar: "https://i.pravatar.cc/150?img=11" },
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: "https://i.pravatar.cc/150?img=11",
        response: "approved",
        comment: "Perfect attendance, truly commendable!",
      },
      {
        id: 2,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "approved",
        comment: "Approved. Fantastic commitment.",
      },
    ],
    status: "Approved",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-02-08",
    updatedAt: "2025-02-08",
  },
  {
    id: 7,
    rewardId: "RWD-000007",
    recipientName: "Hassan Raza",
    recipientAvatar: "https://i.pravatar.cc/150?img=7",
    recipientRole: "Computer Science Teacher",
    category: "Innovation Award",
    name: "Tech Champion Award",
    reason: "Digital curriculum",
    description:
      "Hassan Raza developed a fully digital curriculum for the computer science department and integrated coding bootcamps into regular teaching. Students under his guidance won national level programming competitions.",
    member: { name: "Mr. Tariq Rehman", avatar: "https://i.pravatar.cc/150?img=12" },
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "declined",
        comment: "Budget constraints at present. Please resubmit next quarter.",
      },
    ],
    status: "Declined",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-01-07",
    updatedAt: "2025-01-07",
  },
  {
    id: 8,
    rewardId: "RWD-000008",
    recipientName: "Nadia Rahman",
    recipientAvatar: "https://i.pravatar.cc/150?img=8",
    recipientRole: "Grade 9 - B",
    category: "Star Student",
    name: "Rising Star 2025",
    reason: "Rapid improvement",
    description:
      "Nadia Rahman showed a remarkable improvement in academic performance, moving from average grades to top of class within one semester. Her hard work and perseverance have been truly inspiring.",
    member: { name: "Mrs. Ayesha Noor", avatar: "https://i.pravatar.cc/150?img=11" },
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: "https://i.pravatar.cc/150?img=11",
        response: "approved",
        comment: "Nadia's improvement has been incredible.",
      },
    ],
    status: "Approved",
    hasAttachment: true,
    attachmentType: "Image",
    createdAt: "2025-01-27",
    updatedAt: "2025-01-27",
  },
  {
    id: 9,
    rewardId: "RWD-000009",
    recipientName: "Usman Tariq",
    recipientAvatar: "https://i.pravatar.cc/150?img=9",
    recipientRole: "Physics Teacher",
    category: "Excellence Award",
    name: "Department Head Award",
    reason: "Exceptional guidance",
    description:
      "Usman Tariq has guided the physics department to record-high results while mentoring three junior teachers simultaneously. His organizational skills and academic rigor have elevated the entire department.",
    member: { name: "Dr. Sana Malik", avatar: "https://i.pravatar.cc/150?img=10" },
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "pending",
        comment: "",
      },
      {
        id: 2,
        name: "Mr. Tariq Rehman",
        role: "HR Manager",
        avatar: "https://i.pravatar.cc/150?img=12",
        response: "pending",
        comment: "",
      },
    ],
    status: "Pending",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-02-10",
    updatedAt: "2025-02-10",
  },
  {
    id: 10,
    rewardId: "RWD-000010",
    recipientName: "Zara Hussain",
    recipientAvatar: "https://i.pravatar.cc/150?img=13",
    recipientRole: "Grade 8 - A",
    category: "Leadership Award",
    name: "Junior Leader Award",
    reason: "Club founder",
    description:
      "Zara Hussain founded the school's first environmental awareness club and organized three successful awareness drives. Her leadership at grade 8 level shows remarkable maturity and initiative.",
    member: { name: "Mrs. Ayesha Noor", avatar: "https://i.pravatar.cc/150?img=11" },
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: "https://i.pravatar.cc/150?img=11",
        response: "approved",
        comment: "Speedy approval, great initiative!",
      },
      {
        id: 2,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "approved",
        comment: "Approved.",
      },
    ],
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-01-12",
    updatedAt: "2025-01-12",
  },
  {
    id: 11,
    rewardId: "RWD-000011",
    recipientName: "Bilal Niazi",
    recipientAvatar: "https://i.pravatar.cc/150?img=14",
    recipientRole: "Chemistry Teacher",
    category: "Best Performance",
    name: "Subject Excellence",
    reason: "100% pass rate",
    description:
      "Bilal Niazi achieved a 100% pass rate in his chemistry classes for the first time in the school's history. His thorough preparation of students and innovative revision techniques deserve special recognition.",
    member: { name: "Dr. Sana Malik", avatar: "https://i.pravatar.cc/150?img=10" },
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "approved",
        comment: "Truly a milestone achievement. Approved.",
      },
    ],
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-02-03",
    updatedAt: "2025-02-03",
  },
  {
    id: 12,
    rewardId: "RWD-000012",
    recipientName: "Amna Siddiqui",
    recipientAvatar: "https://i.pravatar.cc/150?img=15",
    recipientRole: "Grade 10 - A",
    category: "Star Student",
    name: "Academic Excellence",
    reason: "Debate champion",
    description:
      "Amna Siddiqui represented the school in the National Inter-School Debate Championship and won the gold medal. She prepared independently and brought tremendous pride to the school community.",
    member: { name: "Mrs. Ayesha Noor", avatar: "https://i.pravatar.cc/150?img=11" },
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: "https://i.pravatar.cc/150?img=11",
        response: "approved",
        comment: "Approved by class teacher.",
      },
      {
        id: 2,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "pending",
        comment: "",
      },
    ],
    status: "In Process",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-01-29",
    updatedAt: "2025-01-29",
  },
  {
    id: 13,
    rewardId: "RWD-000013",
    recipientName: "Mariam Khan",
    recipientAvatar: "https://i.pravatar.cc/150?img=2",
    recipientRole: "Biology Teacher",
    category: "Excellence Award",
    name: "Mentor of the Year",
    reason: "Student mentorship",
    description:
      "Mariam Khan has mentored over 20 students individually outside class hours, helping them overcome academic difficulties. Her selfless commitment to student welfare goes far beyond her job description.",
    member: { name: "Mr. Tariq Rehman", avatar: "https://i.pravatar.cc/150?img=12" },
    approvers: [
      {
        id: 1,
        name: "Mr. Tariq Rehman",
        role: "HR Manager",
        avatar: "https://i.pravatar.cc/150?img=12",
        response: "approved",
        comment: "Mariam's dedication is truly remarkable.",
      },
      {
        id: 2,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "approved",
        comment: "Approved. Well deserved recognition!",
      },
    ],
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-02-01",
    updatedAt: "2025-02-01",
  },
  {
    id: 14,
    rewardId: "RWD-000014",
    recipientName: "Faisal Ahmed",
    recipientAvatar: "https://i.pravatar.cc/150?img=5",
    recipientRole: "Grade 11 - B",
    category: "Attendance Award",
    name: "Punctuality Award",
    reason: "Perfect punctuality",
    description:
      "Faisal Ahmed has not been late to a single class in the entire academic year. His punctuality and consistent presence have set a positive example for his peers and younger students.",
    member: { name: "Mrs. Ayesha Noor", avatar: "https://i.pravatar.cc/150?img=11" },
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: "https://i.pravatar.cc/150?img=11",
        response: "approved",
        comment: "Outstanding punctuality record!",
      },
    ],
    status: "Approved",
    hasAttachment: true,
    attachmentType: "Image",
    createdAt: "2025-02-04",
    updatedAt: "2025-02-04",
  },
  {
    id: 15,
    rewardId: "RWD-000015",
    recipientName: "Sadia Iqbal",
    recipientAvatar: "https://i.pravatar.cc/150?img=6",
    recipientRole: "Urdu Teacher",
    category: "Innovation Award",
    name: "Creative Teaching",
    reason: "Cultural events lead",
    description:
      "Sadia Iqbal organized the school's most successful annual cultural event in recent memory, integrating literature, drama, and art. Her creative approach to teaching Urdu has rekindled student interest in the language.",
    member: { name: "Dr. Sana Malik", avatar: "https://i.pravatar.cc/150?img=10" },
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: "https://i.pravatar.cc/150?img=10",
        response: "declined",
        comment: "Award cycle for this quarter is closed. Please resubmit next cycle.",
      },
    ],
    status: "Declined",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-02-15",
    updatedAt: "2025-02-15",
  },
];

export default REWARDS_DUMMY_DATA;
