/* ── Current user ── */
export const CURRENT_USER = {
  name:  "Admin User",
  email: "admin@schoolsms.edu",
};

/* ── localStorage key ── */
const STORAGE_KEY = "sms_mailbox_emails";

/* ── Timestamp helpers ── */
const now = Date.now();
const h   = (n) => new Date(now - n * 3_600_000).toISOString();
const d   = (n) => new Date(now - n * 86_400_000).toISOString();

/* ── 15 dummy emails ── */
const dummyEmails = [
  /* ── INBOX ── */
  {
    id: "E001",
    from: { name: "Mr. Robert Smith",     email: "robert.smith@schoolsms.edu"  },
    to:   [{ name: "Admin User",           email: "admin@schoolsms.edu"         }],
    cc:   [],
    subject: "Mid-term Exam Schedule Confirmation",
    body: "Dear Admin User,\n\nI am writing to confirm the mid-term examination schedule for the upcoming week. All students in Grades 9–12 will be assessed across their core subjects from Monday to Wednesday. The detailed timetable is attached for your reference and distribution to class teachers.\n\nPlease ensure that the examination halls are booked by tomorrow and that all invigilators have been briefed. Should any subject teacher require additional resources, kindly let me know by end of day today.\n\nBest regards,\nMr. Robert Smith",
    timestamp:     h(1),
    isRead:        false,
    isStarred:     false,
    isImportant:   true,
    folder:        "inbox",
    hasAttachment: true,
    attachmentName: "Exam_Schedule_2025.pdf",
    labels:        ["School"],
  },
  {
    id: "E002",
    from: { name: "Principal David Brown", email: "david.brown@schoolsms.edu"   },
    to:   [{ name: "Admin User",           email: "admin@schoolsms.edu"         }],
    cc:   [],
    subject: "Board Meeting Agenda – This Friday",
    body: "Dear Admin User,\n\nThis is a reminder that our board meeting is confirmed for this Friday at 2:00 PM in the main conference room. Please prepare the following items in advance: the Q1 attendance report, the academic performance summary for all grades, and the budget utilisation update.\n\nKindly circulate the agenda to all board members by Thursday morning. Also please arrange refreshments and ensure the projector and audio system are tested before 1:30 PM.\n\nRegards,\nPrincipal David Brown",
    timestamp:     h(3),
    isRead:        false,
    isStarred:     true,
    isImportant:   false,
    folder:        "inbox",
    hasAttachment: false,
    attachmentName: null,
    labels:        ["Work"],
  },
  {
    id: "E003",
    from: { name: "Ms. Emily Johnson",     email: "emily.johnson@schoolsms.edu" },
    to:   [{ name: "Admin User",           email: "admin@schoolsms.edu"         }],
    cc:   [],
    subject: "Science Fair Results – Class 10",
    body: "Dear Admin,\n\nI am pleased to share the results from our Annual Science Fair for Class 10. The overall participation was excellent, with 28 out of 32 students submitting projects. The top three projects were in the categories of Renewable Energy, Biotechnology, and Robotics.\n\nI will be uploading the full results to the student portal by end of day. The award ceremony is proposed for next Wednesday afternoon. Please confirm your availability so we can send out invitations to parents.\n\nWarm regards,\nMs. Emily Johnson",
    timestamp:     h(5),
    isRead:        true,
    isStarred:     false,
    isImportant:   false,
    folder:        "inbox",
    hasAttachment: false,
    attachmentName: null,
    labels:        ["School"],
  },
  {
    id: "E004",
    from: { name: "Ms. Sarah Williams",    email: "sarah.williams@schoolsms.edu"},
    to:   [{ name: "Admin User",           email: "admin@schoolsms.edu"         }],
    cc:   [{ name: "Mr. Robert Smith",     email: "robert.smith@schoolsms.edu"  }],
    subject: "Updated English Syllabus for Grade 9–11",
    body: "Hi Admin,\n\nThe English department has finalised the updated syllabus for Grades 9, 10, and 11 for the upcoming academic term. The revised document, attached here, includes two new prescribed texts and a restructured composition assessment framework.\n\nAll English teachers have been briefed and are aligned with the changes. I'd appreciate it if the admin office could upload this to the student and parent portals, and also circulate a printed copy to homeroom teachers by Monday.\n\nThank you,\nMs. Sarah Williams",
    timestamp:     h(8),
    isRead:        false,
    isStarred:     false,
    isImportant:   false,
    folder:        "inbox",
    hasAttachment: true,
    attachmentName: "English_Syllabus_Revised_2025.docx",
    labels:        ["School"],
  },
  {
    id: "E005",
    from: { name: "Sports Coach",          email: "coach.pe@schoolsms.edu"      },
    to:   [{ name: "Admin User",           email: "admin@schoolsms.edu"         }],
    cc:   [],
    subject: "Annual Sports Day – Registration Now Open",
    body: "Dear Admin,\n\nAnnual Sports Day registration is now open! Students can register for the following events: 100m Sprint, Long Jump, Shot Put, 4×100m Relay, Football, and Badminton. Registration will remain open until March 5th and must be submitted at the PE office.\n\nThis year we are expecting over 200 student participants. Please help us by announcing the registration drive during morning assembly and having homeroom teachers remind their classes. We also need to confirm the venue booking with the municipal stadium.\n\nThanks,\nSports Coach",
    timestamp:     d(1),
    isRead:        true,
    isStarred:     true,
    isImportant:   true,
    folder:        "inbox",
    hasAttachment: false,
    attachmentName: null,
    labels:        ["School", "Urgent"],
  },
  {
    id: "E006",
    from: { name: "Ahmed Khan",            email: "ahmed.khan@students.schoolsms.edu" },
    to:   [{ name: "Admin User",           email: "admin@schoolsms.edu"               }],
    cc:   [],
    subject: "Request for Assignment Extension – Biology Chapter 5",
    body: "Respected Sir,\n\nI am writing to request a one-day extension for the Biology Chapter 5 assignment. Unfortunately I was unable to complete it on time due to my participation in the inter-school cricket tournament, which ran longer than expected.\n\nI sincerely apologise for the inconvenience and assure you that I will submit the completed work by tomorrow evening without fail. I hope you will consider my request kindly.\n\nThank you,\nAhmed Khan | Grade 11 | Roll No. 14",
    timestamp:     d(1),
    isRead:        true,
    isStarred:     false,
    isImportant:   false,
    folder:        "inbox",
    hasAttachment: false,
    attachmentName: null,
    labels:        ["Personal"],
  },
  {
    id: "E007",
    from: { name: "Library Admin",         email: "library@schoolsms.edu"       },
    to:   [{ name: "Admin User",           email: "admin@schoolsms.edu"         }],
    cc:   [],
    subject: "New Books Added to School Library Catalog",
    body: "Dear Admin User,\n\nWe are pleased to inform you that 45 new books have been added to the school library this week across all subject categories. The complete list is attached as a PDF for your records. Notable additions include updated editions of the STEM reference series and a new fiction collection for the reading club.\n\nStudents may borrow up to 2 books at a time for a 2-week period. Please help us promote library usage by sharing the catalog with all teachers and students.\n\nKind regards,\nLibrary Admin",
    timestamp:     d(2),
    isRead:        true,
    isStarred:     false,
    isImportant:   false,
    folder:        "inbox",
    hasAttachment: true,
    attachmentName: "Library_New_Arrivals_Feb2025.pdf",
    labels:        ["School"],
  },
  {
    id: "E015",
    from: { name: "Dr. Michael Brown",     email: "michael.brown@schoolsms.edu" },
    to:   [{ name: "Admin User",           email: "admin@schoolsms.edu"         }],
    cc:   [],
    subject: "Chemistry Lab Safety Protocol Update – Immediate Action Required",
    body: "Dear Admin,\n\nFollowing the recent laboratory safety audit, the Chemistry department has updated its safety protocols effective immediately. All students must wear safety goggles and lab coats at all times during practical sessions, and the emergency eyewash station has been relocated to the near the main entrance.\n\nI kindly request that you issue a formal notice to all students and parents about these updated protocols, and that the updated safety checklist (attached) be displayed prominently in both chemistry labs. Please confirm receipt and acknowledgement of this communication.\n\nDr. Michael Brown, Chemistry & Physics",
    timestamp:     d(3),
    isRead:        true,
    isStarred:     false,
    isImportant:   true,
    folder:        "inbox",
    hasAttachment: true,
    attachmentName: "Lab_Safety_Protocol_2025.pdf",
    labels:        ["School", "Urgent"],
  },

  /* ── SENT ── */
  {
    id: "E008",
    from: { name: "Admin User",            email: "admin@schoolsms.edu"         },
    to:   [{ name: "Mr. Robert Smith",     email: "robert.smith@schoolsms.edu"  }],
    cc:   [],
    subject: "Re: Mid-term Exam Schedule Confirmation",
    body: "Dear Mr. Smith,\n\nThank you for the confirmation. The examination hall bookings have been finalised and the invigilators have been notified accordingly. I have also arranged for extra copies of the timetable to be printed and distributed to all homeroom teachers.\n\nPlease let me know if there are any last-minute changes to the schedule. We will ensure everything is in order before Monday.\n\nBest regards,\nAdmin User",
    timestamp:     h(2),
    isRead:        true,
    isStarred:     false,
    isImportant:   false,
    folder:        "sent",
    hasAttachment: false,
    attachmentName: null,
    labels:        [],
  },
  {
    id: "E009",
    from: { name: "Admin User",            email: "admin@schoolsms.edu"         },
    to:   [{ name: "All Staff",            email: "staff@schoolsms.edu"         }],
    cc:   [],
    subject: "School Holiday Notice – Upcoming Events & Closures",
    body: "Dear All,\n\nThis is to inform all staff members that the school will be closed on the following dates: March 14th (Founder's Day) and March 22nd (Public Holiday). All scheduled classes and activities on these days will be rescheduled as per the updated academic calendar.\n\nPlease make necessary arrangements for your classes and notify your students accordingly. The updated academic calendar for Term 2 will be circulated separately by end of this week.\n\nRegards,\nAdmin User\nSchool Administration Office",
    timestamp:     d(1),
    isRead:        true,
    isStarred:     false,
    isImportant:   false,
    folder:        "sent",
    hasAttachment: false,
    attachmentName: null,
    labels:        [],
  },
  {
    id: "E010",
    from: { name: "Admin User",            email: "admin@schoolsms.edu"         },
    to:   [{ name: "Principal David Brown",email: "david.brown@schoolsms.edu"   }],
    cc:   [{ name: "Finance Officer",      email: "finance@schoolsms.edu"       }],
    subject: "Q1 Budget Utilisation Report – Attached",
    body: "Dear Principal Brown,\n\nPlease find attached the Q1 Budget Utilisation Report for your review and presentation at the upcoming board meeting. The report covers expenditure across all departments including academic resources, infrastructure maintenance, staff development, and extracurricular activities.\n\nOverall Q1 spending is within 3% of the approved budget. The minor overrun in the sports equipment budget is explained in Section 4 of the report. Please let me know if you need any clarifications before Friday.\n\nBest regards,\nAdmin User",
    timestamp:     d(2),
    isRead:        true,
    isStarred:     false,
    isImportant:   false,
    folder:        "sent",
    hasAttachment: true,
    attachmentName: "Q1_Budget_Report_2025.xlsx",
    labels:        ["Work"],
  },

  /* ── DRAFTS ── */
  {
    id: "E011",
    from: { name: "Admin User",            email: "admin@schoolsms.edu"         },
    to:   [{ name: "Parent Community",     email: "parents@schoolsms.edu"       }],
    cc:   [],
    subject: "Parent-Teacher Meeting Invitation – March 2025",
    body: "Dear Parents and Guardians,\n\nWe cordially invite you to attend the Parent-Teacher Meeting scheduled for Saturday, March 22nd, from 9:00 AM to 12:00 PM at the school premises. This meeting is an important opportunity to discuss your child's academic progress, attendance, and overall well-being.\n\nPlease confirm your attendance by replying to this email or signing the form sent home with your child. Individual slot bookings will be shared separately. We look forward to seeing you.",
    timestamp:     h(12),
    isRead:        true,
    isStarred:     false,
    isImportant:   false,
    folder:        "drafts",
    hasAttachment: false,
    attachmentName: null,
    labels:        [],
  },
  {
    id: "E012",
    from: { name: "Admin User",            email: "admin@schoolsms.edu"         },
    to:   [],
    cc:   [],
    subject: "Annual Function Planning 2025 – Internal Notes",
    body: "Team,\n\nHere are the preliminary notes for the Annual Function planning. We need to confirm the auditorium booking, finalise the programme schedule, and assign responsibilities to department heads.\n\nAction items: confirm AV team by March 1st, finalise student performance list by March 5th, send invitations to chief guest by March 3rd.",
    timestamp:     d(1),
    isRead:        true,
    isStarred:     false,
    isImportant:   false,
    folder:        "drafts",
    hasAttachment: false,
    attachmentName: null,
    labels:        [],
  },

  /* ── TRASH ── */
  {
    id: "E013",
    from: { name: "EdTech Promotions",     email: "promo@edtechplatform.com"    },
    to:   [{ name: "Admin User",           email: "admin@schoolsms.edu"         }],
    cc:   [],
    subject: "You're Invited – Upgrade to Our Premium Education Platform!",
    body: "Dear School Administrator,\n\nCongratulations! Your institution has been selected for an exclusive offer to upgrade to our Premium Education Management Platform. Enjoy unlimited student enrollments, AI-powered analytics, and 24/7 support for just $49/month.\n\nClick the link below to claim your free 30-day trial. This offer expires in 48 hours. Don't miss out on transforming your school's digital experience!\n\nThe EdTech Promotions Team",
    timestamp:     d(3),
    isRead:        true,
    isStarred:     false,
    isImportant:   false,
    folder:        "trash",
    hasAttachment: false,
    attachmentName: null,
    labels:        [],
  },
  {
    id: "E014",
    from: { name: "Monthly Digest",        email: "digest@newsletterservice.com"},
    to:   [{ name: "Admin User",           email: "admin@schoolsms.edu"         }],
    cc:   [],
    subject: "Monthly Newsletter – January Highlights & Updates",
    body: "Hello,\n\nWelcome to the January edition of the Monthly Education Digest. This month we cover: new curriculum frameworks from the Ministry of Education, upcoming national examination dates, teacher professional development workshops, and school management software reviews.\n\nTo unsubscribe from this newsletter, click here. If you have questions, contact support@newsletterservice.com.",
    timestamp:     d(5),
    isRead:        true,
    isStarred:     false,
    isImportant:   false,
    folder:        "trash",
    hasAttachment: false,
    attachmentName: null,
    labels:        [],
  },
];

/* ── localStorage helpers ── */
export const seedMailBox = () => {
  if (!localStorage.getItem(STORAGE_KEY)) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(dummyEmails));
  }
};

export const getEmailsFromStorage = () => {
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored ? JSON.parse(stored) : dummyEmails;
};

export const saveEmailsToStorage = (emails) => {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(emails));
};
