const dummyUsers = [
  {
    id: "USR001",
    name: "Admin User",
    email: "admin@school.com",
    password: "admin123",
    role: "Admin",
    avatar: "",
    department: "Administration",
    phone: "+1 234 567 8901",
  },
  {
    id: "USR002",
    name: "John Teacher",
    email: "teacher@school.com",
    password: "teacher123",
    role: "Teacher",
    avatar: "",
    department: "Mathematics",
    phone: "+1 234 567 8902",
  },
  {
    id: "USR003",
    name: "Sarah Student",
    email: "student@school.com",
    password: "student123",
    role: "Student",
    avatar: "",
    department: "Class X-A",
    phone: "+1 234 567 8903",
  },
  {
    id: "USR004",
    name: "David Parent",
    email: "parent@school.com",
    password: "parent123",
    role: "Parent",
    avatar: "",
    department: "Guardian",
    phone: "+1 234 567 8904",
  },
  {
    id: "USR005",
    name: "Maria Cleaning",
    email: "cleaning@school.com",
    password: "cleaning123",
    role: "Cleaning Staff",
    avatar: "",
    department: "Maintenance",
    phone: "+1 234 567 8905",
  },
  {
    id: "USR006",
    name: "James Other",
    email: "other@school.com",
    password: "other123",
    role: "Other Staff",
    avatar: "",
    department: "General",
    phone: "+1 234 567 8906",
  },
];

export default dummyUsers;
