const WARNINGS_DUMMY_DATA = [
  {
    id: 1,
    warningId: "WRN-000001",
    recipientName: "Ahmed Khan",
    recipientAvatar: "https://i.pravatar.cc/150?img=1",
    recipientRole: "Mathematics Teacher",
    category: "Misconduct",
    warningTo: { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    approvers: [
      { id: 1, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Approved", comment: "Warning issued after thorough review." },
    ],
    description: "Ahmed Khan was observed engaging in disruptive behavior during a faculty meeting, interrupting colleagues and refusing to follow the meeting agenda. This is the first formal warning issued regarding such conduct.",
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-01-14",
    updatedAt: "2025-01-15",
  },
  {
    id: 2,
    warningId: "WRN-000002",
    recipientName: "Sara Ali",
    recipientAvatar: "https://i.pravatar.cc/150?img=2",
    recipientRole: "Grade 9 - A",
    category: "Late Attendance",
    warningTo: { name: "Sara Ali", avatar: "https://i.pravatar.cc/150?img=2" },
    approvers: [
      { id: 1, name: "Omar Farooq", role: "Vice Principal", avatar: "https://i.pravatar.cc/150?img=11", response: "Pending", comment: "" },
    ],
    description: "Sara Ali has been late to school on 8 consecutive occasions this month without providing any valid reason or prior notification. Her continued tardiness is affecting her academic performance and class routine.",
    status: "Pending",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-01-20",
    updatedAt: "2025-01-20",
  },
  {
    id: 3,
    warningId: "WRN-000003",
    recipientName: "Muhammad Bilal",
    recipientAvatar: "https://i.pravatar.cc/150?img=3",
    recipientRole: "Science Teacher",
    category: "Poor Performance",
    warningTo: { name: "Muhammad Bilal", avatar: "https://i.pravatar.cc/150?img=3" },
    approvers: [
      { id: 1, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Approved", comment: "Performance concerns noted." },
      { id: 2, name: "Nadia Rahman", role: "HR Manager", avatar: "https://i.pravatar.cc/150?img=12", response: "Approved", comment: "PIP will follow." },
    ],
    description: "Muhammad Bilal's student pass rates have dropped below the acceptable threshold for two consecutive terms. Despite prior verbal counseling, no measurable improvement has been observed in teaching outcomes.",
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-02-03",
    updatedAt: "2025-02-05",
  },
  {
    id: 4,
    warningId: "WRN-000004",
    recipientName: "Fatima Sheikh",
    recipientAvatar: "https://i.pravatar.cc/150?img=4",
    recipientRole: "Grade 10 - B",
    category: "Dress Code Violation",
    warningTo: { name: "Fatima Sheikh", avatar: "https://i.pravatar.cc/150?img=4" },
    approvers: [
      { id: 1, name: "Hassan Raza", role: "Discipline Head", avatar: "https://i.pravatar.cc/150?img=13", response: "Approved", comment: "Student was reminded of the uniform policy." },
    ],
    description: "Fatima Sheikh has repeatedly violated the school dress code policy by wearing non-uniform attire on five separate occasions. She was verbally warned twice before this formal warning was issued.",
    status: "Approved",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-02-10",
    updatedAt: "2025-02-11",
  },
  {
    id: 5,
    warningId: "WRN-000005",
    recipientName: "Omar Farooq",
    recipientAvatar: "https://i.pravatar.cc/150?img=5",
    recipientRole: "English Teacher",
    category: "Insubordination",
    warningTo: { name: "Omar Farooq", avatar: "https://i.pravatar.cc/150?img=5" },
    approvers: [
      { id: 1, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Pending", comment: "" },
      { id: 2, name: "Ayesha Malik", role: "Deputy Principal", avatar: "https://i.pravatar.cc/150?img=14", response: "Pending", comment: "" },
    ],
    description: "Omar Farooq refused a direct instruction from the department head regarding lesson plan submission deadlines and was openly dismissive during a performance review session. The behavior was witnessed by two other staff members.",
    status: "In Process",
    hasAttachment: true,
    attachmentType: "Image",
    createdAt: "2025-02-15",
    updatedAt: "2025-02-16",
  },
  {
    id: 6,
    warningId: "WRN-000006",
    recipientName: "Ayesha Malik",
    recipientAvatar: "https://i.pravatar.cc/150?img=6",
    recipientRole: "Grade 8 - C",
    category: "Academic Dishonesty",
    warningTo: { name: "Ayesha Malik", avatar: "https://i.pravatar.cc/150?img=6" },
    approvers: [
      { id: 1, name: "Hassan Raza", role: "Discipline Head", avatar: "https://i.pravatar.cc/150?img=13", response: "Approved", comment: "Incident confirmed by exam supervisor." },
      { id: 2, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Declined", comment: "Insufficient evidence for formal action." },
    ],
    description: "Ayesha Malik was caught using a concealed cheat sheet during the mid-term mathematics examination. The invigilator confiscated the material and the incident was reported to the academic integrity committee.",
    status: "Declined",
    hasAttachment: true,
    attachmentType: "Image",
    createdAt: "2025-03-01",
    updatedAt: "2025-03-03",
  },
  {
    id: 7,
    warningId: "WRN-000007",
    recipientName: "Hassan Raza",
    recipientAvatar: "https://i.pravatar.cc/150?img=7",
    recipientRole: "Physics Teacher",
    category: "Late Attendance",
    warningTo: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=7" },
    approvers: [
      { id: 1, name: "Nadia Rahman", role: "HR Manager", avatar: "https://i.pravatar.cc/150?img=12", response: "Approved", comment: "Attendance records reviewed and confirmed." },
    ],
    description: "Hassan Raza has accumulated 12 instances of late arrivals in the current academic term. His late arrivals result in classes starting without proper supervision, impacting the learning environment for students.",
    status: "Approved",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-03-08",
    updatedAt: "2025-03-09",
  },
  {
    id: 8,
    warningId: "WRN-000008",
    recipientName: "Nadia Rahman",
    recipientAvatar: "https://i.pravatar.cc/150?img=8",
    recipientRole: "Grade 11 - A",
    category: "Misconduct",
    warningTo: { name: "Nadia Rahman", avatar: "https://i.pravatar.cc/150?img=8" },
    approvers: [
      { id: 1, name: "Omar Farooq", role: "Vice Principal", avatar: "https://i.pravatar.cc/150?img=11", response: "Pending", comment: "" },
    ],
    description: "Nadia Rahman engaged in a verbal altercation with a classmate in the school hallway, using inappropriate language in the presence of junior students. The incident was reported by a supervising teacher on duty.",
    status: "Pending",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-03-15",
    updatedAt: "2025-03-15",
  },
  {
    id: 9,
    warningId: "WRN-000009",
    recipientName: "Zainab Hussain",
    recipientAvatar: "https://i.pravatar.cc/150?img=9",
    recipientRole: "Chemistry Teacher",
    category: "Poor Performance",
    warningTo: { name: "Zainab Hussain", avatar: "https://i.pravatar.cc/150?img=9" },
    approvers: [
      { id: 1, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Approved", comment: "Performance improvement plan initiated." },
      { id: 2, name: "Ayesha Malik", role: "Deputy Principal", avatar: "https://i.pravatar.cc/150?img=14", response: "Approved", comment: "Monthly reviews scheduled." },
    ],
    description: "Zainab Hussain's lab sessions have been reported as inadequately prepared, with students frequently completing practicals without proper safety briefings. Parent complaints have been received on three separate occasions.",
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-03-22",
    updatedAt: "2025-03-24",
  },
  {
    id: 10,
    warningId: "WRN-000010",
    recipientName: "Tariq Mehmood",
    recipientAvatar: "https://i.pravatar.cc/150?img=15",
    recipientRole: "Grade 7 - B",
    category: "Dress Code Violation",
    warningTo: { name: "Tariq Mehmood", avatar: "https://i.pravatar.cc/150?img=15" },
    approvers: [
      { id: 1, name: "Hassan Raza", role: "Discipline Head", avatar: "https://i.pravatar.cc/150?img=13", response: "Pending", comment: "" },
    ],
    description: "Tariq Mehmood has arrived at school without the prescribed uniform on seven occasions this term. When questioned, he stated his family was unaware of the dress code requirements, though the policy was communicated at enrollment.",
    status: "In Process",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-04-02",
    updatedAt: "2025-04-03",
  },
  {
    id: 11,
    warningId: "WRN-000011",
    recipientName: "Sadia Butt",
    recipientAvatar: "https://i.pravatar.cc/150?img=11",
    recipientRole: "Urdu Teacher",
    category: "Insubordination",
    warningTo: { name: "Sadia Butt", avatar: "https://i.pravatar.cc/150?img=11" },
    approvers: [
      { id: 1, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Declined", comment: "The situation was a misunderstanding." },
    ],
    description: "Sadia Butt refused to attend the mandatory teacher training session citing personal reasons without prior approval or documentation. This is the second such instance within the current school year.",
    status: "Declined",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-04-10",
    updatedAt: "2025-04-12",
  },
  {
    id: 12,
    warningId: "WRN-000012",
    recipientName: "Imran Qureshi",
    recipientAvatar: "https://i.pravatar.cc/150?img=12",
    recipientRole: "Grade 12 - Science",
    category: "Academic Dishonesty",
    warningTo: { name: "Imran Qureshi", avatar: "https://i.pravatar.cc/150?img=12" },
    approvers: [
      { id: 1, name: "Hassan Raza", role: "Discipline Head", avatar: "https://i.pravatar.cc/150?img=13", response: "Approved", comment: "Evidence confirmed by two examiners." },
      { id: 2, name: "Nadia Rahman", role: "HR Manager", avatar: "https://i.pravatar.cc/150?img=12", response: "Approved", comment: "Record added to student file." },
    ],
    description: "Imran Qureshi submitted an assignment that was found to contain directly plagiarized content from an online source without any citation. Similarity index showed 87% match upon running the document through detection software.",
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-04-18",
    updatedAt: "2025-04-20",
  },
  {
    id: 13,
    warningId: "WRN-000013",
    recipientName: "Rabia Nawaz",
    recipientAvatar: "https://i.pravatar.cc/150?img=13",
    recipientRole: "Computer Science Teacher",
    category: "Misconduct",
    warningTo: { name: "Rabia Nawaz", avatar: "https://i.pravatar.cc/150?img=13" },
    approvers: [
      { id: 1, name: "Omar Farooq", role: "Vice Principal", avatar: "https://i.pravatar.cc/150?img=11", response: "Pending", comment: "" },
      { id: 2, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Pending", comment: "" },
    ],
    description: "Rabia Nawaz was reported for sharing confidential student assessment data in an unauthorized group chat. This constitutes a breach of student data privacy policy and professional conduct standards of the institution.",
    status: "In Process",
    hasAttachment: true,
    attachmentType: "Image",
    createdAt: "2025-05-05",
    updatedAt: "2025-05-06",
  },
  {
    id: 14,
    warningId: "WRN-000014",
    recipientName: "Kamran Shah",
    recipientAvatar: "https://i.pravatar.cc/150?img=14",
    recipientRole: "Grade 6 - A",
    category: "Late Attendance",
    warningTo: { name: "Kamran Shah", avatar: "https://i.pravatar.cc/150?img=14" },
    approvers: [
      { id: 1, name: "Hassan Raza", role: "Discipline Head", avatar: "https://i.pravatar.cc/150?img=13", response: "Approved", comment: "Parents have been notified." },
    ],
    description: "Kamran Shah has been recorded as absent for first period on 10 school days this term without any approved leave or parental notification. The class teacher has attempted contact with the family on multiple occasions.",
    status: "Approved",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-05-12",
    updatedAt: "2025-05-13",
  },
  {
    id: 15,
    warningId: "WRN-000015",
    recipientName: "Lubna Akhtar",
    recipientAvatar: "https://i.pravatar.cc/150?img=15",
    recipientRole: "Biology Teacher",
    category: "Poor Performance",
    warningTo: { name: "Lubna Akhtar", avatar: "https://i.pravatar.cc/150?img=15" },
    approvers: [
      { id: 1, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Pending", comment: "" },
    ],
    description: "Lubna Akhtar has failed to submit end-of-term assessment reports for three consecutive classes. Peer observations noted that lesson objectives are frequently not met and student engagement levels remain critically low.",
    status: "Pending",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-05-20",
    updatedAt: "2025-05-20",
  },
];

export default WARNINGS_DUMMY_DATA;
