const COMPLAINTS_DUMMY_DATA = [
  {
    id: 1,
    complaintId: "CMP-000001",
    recipientName: "Ahmed Khan",
    recipientAvatar: "https://i.pravatar.cc/150?img=1",
    recipientRole: "Mathematics Teacher",
    category: "Harassment",
    complainOf: { name: "Dr. Sana Malik", avatar: "https://i.pravatar.cc/150?img=10" },
    approvers: [
      { id: 1, name: "Mr. Tariq Rehman", role: "HR Manager", avatar: "https://i.pravatar.cc/150?img=11", response: "Approved", comment: "Reviewed and verified the complaint." },
    ],
    description: "Ahmed Khan reported being subjected to repeated verbal harassment by Dr. Sana Malik during departmental meetings. The comments were demeaning and made in front of other staff members on multiple occasions.",
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-01-14",
    updatedAt: "2025-01-15",
  },
  {
    id: 2,
    complaintId: "CMP-000002",
    recipientName: "Sara Ali",
    recipientAvatar: "https://i.pravatar.cc/150?img=2",
    recipientRole: "Grade 9 - A",
    category: "Bullying",
    complainOf: { name: "Omar Farooq", avatar: "https://i.pravatar.cc/150?img=5" },
    approvers: [
      { id: 1, name: "Hassan Raza", role: "Discipline Head", avatar: "https://i.pravatar.cc/150?img=13", response: "Pending", comment: "" },
    ],
    description: "Sara Ali has submitted a complaint regarding persistent bullying behavior from Omar Farooq. The student reports being intentionally excluded from group activities and targeted with mocking remarks daily.",
    status: "Pending",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-01-20",
    updatedAt: "2025-01-20",
  },
  {
    id: 3,
    complaintId: "CMP-000003",
    recipientName: "Muhammad Bilal",
    recipientAvatar: "https://i.pravatar.cc/150?img=3",
    recipientRole: "Science Teacher",
    category: "Academic Issue",
    complainOf: { name: "Nadia Rahman", avatar: "https://i.pravatar.cc/150?img=8" },
    approvers: [
      { id: 1, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Approved", comment: "Investigation confirmed the grading discrepancy." },
      { id: 2, name: "Mr. Tariq Rehman", role: "HR Manager", avatar: "https://i.pravatar.cc/150?img=11", response: "Approved", comment: "Records have been corrected accordingly." },
    ],
    description: "Muhammad Bilal has raised a formal complaint about unfair grading practices by Nadia Rahman. He claims his exam papers were marked significantly lower than peers with similar answers without any justification.",
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-02-03",
    updatedAt: "2025-02-05",
  },
  {
    id: 4,
    complaintId: "CMP-000004",
    recipientName: "Fatima Sheikh",
    recipientAvatar: "https://i.pravatar.cc/150?img=4",
    recipientRole: "Grade 10 - B",
    category: "Facilities Issue",
    complainOf: { name: "Zainab Hussain", avatar: "https://i.pravatar.cc/150?img=9" },
    approvers: [
      { id: 1, name: "Hassan Raza", role: "Discipline Head", avatar: "https://i.pravatar.cc/150?img=13", response: "Approved", comment: "Maintenance team has been notified." },
    ],
    description: "Fatima Sheikh has complained about the deteriorating condition of the science laboratory facilities. Equipment is broken and safety hazards have been present for weeks without any corrective action taken.",
    status: "Approved",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-02-10",
    updatedAt: "2025-02-12",
  },
  {
    id: 5,
    complaintId: "CMP-000005",
    recipientName: "Omar Farooq",
    recipientAvatar: "https://i.pravatar.cc/150?img=5",
    recipientRole: "English Teacher",
    category: "Staff Conduct",
    complainOf: { name: "Ayesha Malik", avatar: "https://i.pravatar.cc/150?img=6" },
    approvers: [
      { id: 1, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Pending", comment: "" },
      { id: 2, name: "Nadia Rahman", role: "HR Manager", avatar: "https://i.pravatar.cc/150?img=8", response: "Pending", comment: "" },
    ],
    description: "Omar Farooq has filed a complaint against Ayesha Malik for unprofessional conduct during a staff meeting. The incident involved inappropriate remarks and disrespectful behavior witnessed by multiple colleagues.",
    status: "In Process",
    hasAttachment: true,
    attachmentType: "Image",
    createdAt: "2025-02-15",
    updatedAt: "2025-02-16",
  },
  {
    id: 6,
    complaintId: "CMP-000006",
    recipientName: "Ayesha Malik",
    recipientAvatar: "https://i.pravatar.cc/150?img=6",
    recipientRole: "Grade 8 - C",
    category: "Safety Concern",
    complainOf: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=7" },
    approvers: [
      { id: 1, name: "Mr. Tariq Rehman", role: "HR Manager", avatar: "https://i.pravatar.cc/150?img=11", response: "Approved", comment: "Safety inspection has been scheduled." },
      { id: 2, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Declined", comment: "Insufficient evidence to escalate at this time." },
    ],
    description: "Ayesha Malik reported a safety concern regarding loose electrical wiring in the Grade 8 corridor. The issue has been visible for over a month and poses a serious risk to students and staff passing by.",
    status: "Declined",
    hasAttachment: true,
    attachmentType: "Image",
    createdAt: "2025-03-01",
    updatedAt: "2025-03-03",
  },
  {
    id: 7,
    complaintId: "CMP-000007",
    recipientName: "Hassan Raza",
    recipientAvatar: "https://i.pravatar.cc/150?img=7",
    recipientRole: "Physics Teacher",
    category: "Discrimination",
    complainOf: { name: "Rabia Nawaz", avatar: "https://i.pravatar.cc/150?img=13" },
    approvers: [
      { id: 1, name: "Nadia Rahman", role: "HR Manager", avatar: "https://i.pravatar.cc/150?img=8", response: "Approved", comment: "Complaint has been thoroughly investigated." },
    ],
    description: "Hassan Raza has raised a discrimination complaint against Rabia Nawaz for consistently assigning less favorable duties and schedules based on personal bias. The pattern has been observed over the past three months.",
    status: "Approved",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-03-08",
    updatedAt: "2025-03-10",
  },
  {
    id: 8,
    complaintId: "CMP-000008",
    recipientName: "Nadia Rahman",
    recipientAvatar: "https://i.pravatar.cc/150?img=8",
    recipientRole: "Grade 11 - A",
    category: "Harassment",
    complainOf: { name: "Kamran Shah", avatar: "https://i.pravatar.cc/150?img=14" },
    approvers: [
      { id: 1, name: "Hassan Raza", role: "Discipline Head", avatar: "https://i.pravatar.cc/150?img=7", response: "Pending", comment: "" },
    ],
    description: "Nadia Rahman has submitted a harassment complaint against Kamran Shah for repeatedly making unwanted comments about her personal life. The behavior has continued despite previous verbal requests to stop.",
    status: "Pending",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-03-15",
    updatedAt: "2025-03-15",
  },
  {
    id: 9,
    complaintId: "CMP-000009",
    recipientName: "Zainab Hussain",
    recipientAvatar: "https://i.pravatar.cc/150?img=9",
    recipientRole: "Chemistry Teacher",
    category: "Academic Issue",
    complainOf: { name: "Sadia Butt", avatar: "https://i.pravatar.cc/150?img=11" },
    approvers: [
      { id: 1, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Approved", comment: "Curriculum review has been initiated." },
      { id: 2, name: "Mr. Tariq Rehman", role: "HR Manager", avatar: "https://i.pravatar.cc/150?img=11", response: "Approved", comment: "Teaching standards review scheduled." },
    ],
    description: "Zainab Hussain has raised a formal complaint about inadequate curriculum coverage by Sadia Butt. Key topics from the syllabus have not been taught and students are underprepared for their examinations.",
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-03-22",
    updatedAt: "2025-03-24",
  },
  {
    id: 10,
    complaintId: "CMP-000010",
    recipientName: "Tariq Mehmood",
    recipientAvatar: "https://i.pravatar.cc/150?img=15",
    recipientRole: "Grade 7 - B",
    category: "Bullying",
    complainOf: { name: "Imran Qureshi", avatar: "https://i.pravatar.cc/150?img=12" },
    approvers: [
      { id: 1, name: "Hassan Raza", role: "Discipline Head", avatar: "https://i.pravatar.cc/150?img=7", response: "Pending", comment: "" },
    ],
    description: "Tariq Mehmood has reported ongoing bullying by Imran Qureshi in the school hallways and during break time. The situation has escalated from verbal taunting to physical intimidation over the past two weeks.",
    status: "In Process",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-04-02",
    updatedAt: "2025-04-04",
  },
  {
    id: 11,
    complaintId: "CMP-000011",
    recipientName: "Sadia Butt",
    recipientAvatar: "https://i.pravatar.cc/150?img=11",
    recipientRole: "Urdu Teacher",
    category: "Staff Conduct",
    complainOf: { name: "Lubna Akhtar", avatar: "https://i.pravatar.cc/150?img=15" },
    approvers: [
      { id: 1, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Declined", comment: "After review, the complaint was found to be unsubstantiated." },
    ],
    description: "Sadia Butt has filed a complaint about Lubna Akhtar's conduct during joint staff sessions. The alleged behavior includes interrupting presentations and dismissing input from colleagues in a disrespectful manner.",
    status: "Declined",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-04-10",
    updatedAt: "2025-04-12",
  },
  {
    id: 12,
    complaintId: "CMP-000012",
    recipientName: "Imran Qureshi",
    recipientAvatar: "https://i.pravatar.cc/150?img=12",
    recipientRole: "Grade 12 - Science",
    category: "Facilities Issue",
    complainOf: { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    approvers: [
      { id: 1, name: "Hassan Raza", role: "Discipline Head", avatar: "https://i.pravatar.cc/150?img=7", response: "Approved", comment: "Facilities team has confirmed the issue." },
      { id: 2, name: "Nadia Rahman", role: "HR Manager", avatar: "https://i.pravatar.cc/150?img=8", response: "Approved", comment: "Repair work has been scheduled." },
    ],
    description: "Imran Qureshi has raised a complaint about the inadequate ventilation and extreme heat in the Grade 12 classrooms. The conditions are affecting student concentration and well-being during examination preparation.",
    status: "Approved",
    hasAttachment: true,
    attachmentType: "PDF",
    createdAt: "2025-04-18",
    updatedAt: "2025-04-20",
  },
  {
    id: 13,
    complaintId: "CMP-000013",
    recipientName: "Rabia Nawaz",
    recipientAvatar: "https://i.pravatar.cc/150?img=13",
    recipientRole: "Computer Science Teacher",
    category: "Discrimination",
    complainOf: { name: "Muhammad Bilal", avatar: "https://i.pravatar.cc/150?img=3" },
    approvers: [
      { id: 1, name: "Mr. Tariq Rehman", role: "HR Manager", avatar: "https://i.pravatar.cc/150?img=11", response: "Pending", comment: "" },
      { id: 2, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Pending", comment: "" },
    ],
    description: "Rabia Nawaz has filed a discrimination complaint against Muhammad Bilal for differential treatment in resource allocation and professional development opportunities. The disparity has persisted throughout the academic year.",
    status: "In Process",
    hasAttachment: true,
    attachmentType: "Image",
    createdAt: "2025-05-05",
    updatedAt: "2025-05-06",
  },
  {
    id: 14,
    complaintId: "CMP-000014",
    recipientName: "Kamran Shah",
    recipientAvatar: "https://i.pravatar.cc/150?img=14",
    recipientRole: "Administrator",
    category: "Safety Concern",
    complainOf: { name: "Omar Farooq", avatar: "https://i.pravatar.cc/150?img=5" },
    approvers: [
      { id: 1, name: "Hassan Raza", role: "Discipline Head", avatar: "https://i.pravatar.cc/150?img=7", response: "Approved", comment: "Safety protocols have been updated." },
    ],
    description: "Kamran Shah has submitted a safety concern regarding inadequate fire exit signage and blocked emergency pathways in the administration block. A fire drill last week revealed multiple compliance failures.",
    status: "Approved",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-05-12",
    updatedAt: "2025-05-14",
  },
  {
    id: 15,
    complaintId: "CMP-000015",
    recipientName: "Lubna Akhtar",
    recipientAvatar: "https://i.pravatar.cc/150?img=15",
    recipientRole: "Biology Teacher",
    category: "Staff Conduct",
    complainOf: { name: "Fatima Sheikh", avatar: "https://i.pravatar.cc/150?img=4" },
    approvers: [
      { id: 1, name: "Dr. Sana Malik", role: "Principal", avatar: "https://i.pravatar.cc/150?img=10", response: "Pending", comment: "" },
    ],
    description: "Lubna Akhtar has raised a formal complaint about Fatima Sheikh's conduct in the staff room. The alleged behavior involves spreading unverified rumors and creating a hostile environment among the teaching staff.",
    status: "Pending",
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-05-20",
    updatedAt: "2025-05-20",
  },
];

export default COMPLAINTS_DUMMY_DATA;
