const PAGES_DUMMY_DATA = [
  {
    id: 1,
    pageId: "PGE-000001",
    name: "School Rules",
    description: "Comprehensive list of behavioral and academic rules every student must follow on school premises.",
    status: "Published",
    tags: ["rules", "policy"],
    collaborators: [
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2" },
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    reader: "All Students",
    creator: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    createDate: "2024-08-01",
    updateDate: "2025-01-15",
    privacy: "Public",
  },
  {
    id: 2,
    pageId: "PGE-000002",
    name: "Academic Calendar",
    description: "Full academic year calendar including term dates, holidays, examination windows, and key events.",
    status: "Published",
    tags: ["academic", "sedw"],
    collaborators: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    ],
    reader: "Staff & Students",
    creator: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    createDate: "2024-09-01",
    updateDate: "2025-01-20",
    privacy: "Public",
  },
  {
    id: 3,
    pageId: "PGE-000003",
    name: "Admission Guidelines",
    description: "Step-by-step guide for new student admissions covering eligibility, documentation, and test requirements.",
    status: "Not Published",
    tags: ["vbhh", "admin"],
    collaborators: [
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5" },
      { name: "Ahmed Khan",    avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Hina Khan",     avatar: "https://i.pravatar.cc/150?img=17" },
    ],
    reader: "",
    creator: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    createDate: "2025-01-10",
    updateDate: "2025-02-05",
    privacy: "Private",
  },
  {
    id: 4,
    pageId: "PGE-000004",
    name: "Fee Structure",
    description: "Detailed fee schedule for all grades including tuition, transport, and extra-curricular charges.",
    status: "Published",
    tags: ["sdfre", "admin"],
    collaborators: [
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    ],
    reader: "Parents",
    creator: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    createDate: "2024-08-15",
    updateDate: "2025-01-10",
    privacy: "Public",
  },
  {
    id: 5,
    pageId: "PGE-000005",
    name: "Exam Schedule",
    description: "Mid-term and final examination timetable for all grades with hall and invigilator assignments.",
    status: "Published",
    tags: ["axmn", "exam"],
    collaborators: [
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2" },
      { name: "Bilal Ahmad",   avatar: "https://i.pravatar.cc/150?img=16" },
    ],
    reader: "All Students",
    creator: { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    createDate: "2025-01-05",
    updateDate: "2025-02-10",
    privacy: "Public",
  },
  {
    id: 6,
    pageId: "PGE-000006",
    name: "Holiday List",
    description: "Official list of public and school holidays for the current academic year.",
    status: "Published",
    tags: ["bztp"],
    collaborators: [
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    reader: "Staff & Students",
    creator: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    createDate: "2024-08-01",
    updateDate: "2025-01-01",
    privacy: "Public",
  },
  {
    id: 7,
    pageId: "PGE-000007",
    name: "Staff Directory",
    description: "Contact information and role details for all teaching and administrative staff members.",
    status: "Not Published",
    tags: ["cnrl", "staff"],
    collaborators: [
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5" },
      { name: "Usman Ali",     avatar: "https://i.pravatar.cc/150?img=18" },
    ],
    reader: "",
    creator: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    createDate: "2025-01-15",
    updateDate: "2025-02-18",
    privacy: "Private",
  },
  {
    id: 8,
    pageId: "PGE-000008",
    name: "Student Handbook",
    description: "Complete guide for students covering conduct, academic expectations, and available support services.",
    status: "Published",
    tags: ["dkpx", "guide"],
    collaborators: [
      { name: "Ahmed Khan",    avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Sana Tariq",    avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    reader: "All Students",
    creator: { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    createDate: "2024-09-01",
    updateDate: "2025-01-25",
    privacy: "Public",
  },
  {
    id: 9,
    pageId: "PGE-000009",
    name: "Library Rules",
    description: "Guidelines for using the school library including borrowing limits, return policies, and quiet zones.",
    status: "Published",
    tags: ["efgt"],
    collaborators: [
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    reader: "All Students",
    creator: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    createDate: "2024-08-20",
    updateDate: "2025-01-08",
    privacy: "Public",
  },
  {
    id: 10,
    pageId: "PGE-000010",
    name: "Lab Safety Guidelines",
    description: "Safety protocols for science and computer labs, including equipment handling and emergency procedures.",
    status: "Published",
    tags: ["fxvr", "safety"],
    collaborators: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
      { name: "Bilal Ahmad",   avatar: "https://i.pravatar.cc/150?img=16" },
    ],
    reader: "Science Students",
    creator: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    createDate: "2024-08-10",
    updateDate: "2025-01-12",
    privacy: "Public",
  },
  {
    id: 11,
    pageId: "PGE-000011",
    name: "Sports Schedule",
    description: "Weekly sports practice timetable and inter-house competition fixtures for the current term.",
    status: "Not Published",
    tags: ["grwb", "sport"],
    collaborators: [
      { name: "Ahmed Khan",    avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Hina Khan",     avatar: "https://i.pravatar.cc/150?img=17" },
    ],
    reader: "",
    creator: { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    createDate: "2025-01-20",
    updateDate: "2025-02-20",
    privacy: "Public",
  },
  {
    id: 12,
    pageId: "PGE-000012",
    name: "Parent Guidelines",
    description: "Information for parents on school communication, PTM schedules, and student progress reporting.",
    status: "Published",
    tags: ["hjkl", "info"],
    collaborators: [
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2" },
    ],
    reader: "Parents",
    creator: { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    createDate: "2024-09-10",
    updateDate: "2025-01-30",
    privacy: "Public",
  },
  {
    id: 13,
    pageId: "PGE-000013",
    name: "Scholarship Info",
    description: "Details on available merit and need-based scholarships, eligibility criteria, and application process.",
    status: "Published",
    tags: ["imno", "sedw"],
    collaborators: [
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5" },
      { name: "Usman Ali",     avatar: "https://i.pravatar.cc/150?img=18" },
    ],
    reader: "Grade 9-12",
    creator: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    createDate: "2024-10-01",
    updateDate: "2025-02-01",
    privacy: "Public",
  },
  {
    id: 14,
    pageId: "PGE-000014",
    name: "Transport Schedule",
    description: "Bus routes, pick-up timings, and drop-off points for all registered school transport users.",
    status: "Not Published",
    tags: ["axmn"],
    collaborators: [
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    reader: "",
    creator: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    createDate: "2025-01-25",
    updateDate: "2025-02-22",
    privacy: "Private",
  },
  {
    id: 15,
    pageId: "PGE-000015",
    name: "Canteen Menu",
    description: "Daily and weekly canteen menu with pricing, nutritional highlights, and special meal options.",
    status: "Published",
    tags: ["vbhh"],
    collaborators: [
      { name: "Sana Tariq",    avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    reader: "All Students",
    creator: { name: "Sana Tariq", avatar: "https://i.pravatar.cc/150?img=19" },
    createDate: "2024-08-25",
    updateDate: "2025-02-03",
    privacy: "Public",
  },
  {
    id: 16,
    pageId: "PGE-000016",
    name: "Club Activities",
    description: "Overview of all registered school clubs, their meeting schedules, coordinators, and how to join.",
    status: "Published",
    tags: ["cnrl", "event"],
    collaborators: [
      { name: "Bilal Ahmad",   avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Hina Khan",     avatar: "https://i.pravatar.cc/150?img=17" },
    ],
    reader: "All Students",
    creator: { name: "Bilal Ahmad", avatar: "https://i.pravatar.cc/150?img=16" },
    createDate: "2024-09-15",
    updateDate: "2025-01-18",
    privacy: "Public",
  },
  {
    id: 17,
    pageId: "PGE-000017",
    name: "Award Criteria",
    description: "Criteria and selection process for academic excellence awards, sports trophies, and best student prizes.",
    status: "Not Published",
    tags: ["dkpx", "sdfre"],
    collaborators: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    ],
    reader: "",
    creator: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    createDate: "2025-02-01",
    updateDate: "2025-02-25",
    privacy: "Private",
  },
  {
    id: 18,
    pageId: "PGE-000018",
    name: "Code of Conduct",
    description: "Detailed code of conduct for students and staff outlining expected behavior and disciplinary actions.",
    status: "Published",
    tags: ["policy", "rules"],
    collaborators: [
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2" },
    ],
    reader: "All Staff & Students",
    creator: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    createDate: "2024-08-01",
    updateDate: "2025-01-05",
    privacy: "Public",
  },
  {
    id: 19,
    pageId: "PGE-000019",
    name: "Emergency Procedures",
    description: "Fire drill procedures, first-aid protocols, and emergency contact numbers for the school premises.",
    status: "Published",
    tags: ["safety", "bztp"],
    collaborators: [
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Usman Ali",     avatar: "https://i.pravatar.cc/150?img=18" },
    ],
    reader: "All Staff",
    creator: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    createDate: "2024-09-20",
    updateDate: "2025-01-22",
    privacy: "Public",
  },
  {
    id: 20,
    pageId: "PGE-000020",
    name: "Contact Directory",
    description: "Complete directory of department contacts, helpline numbers, and administrative office details.",
    status: "Not Published",
    tags: ["info", "grwb"],
    collaborators: [
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5" },
      { name: "Ahmed Khan",    avatar: "https://i.pravatar.cc/150?img=1" },
    ],
    reader: "",
    creator: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    createDate: "2025-01-28",
    updateDate: "2025-02-26",
    privacy: "Private",
  },
  {
    id: 21,
    pageId: "PGE-000021",
    name: "Alumni Page",
    description: "Dedicated page for school alumni featuring notable graduates, reunion event details, and networking info.",
    status: "Published",
    tags: ["imno"],
    collaborators: [
      { name: "Sana Tariq",    avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    reader: "Alumni",
    creator: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    createDate: "2024-10-10",
    updateDate: "2025-02-08",
    privacy: "Public",
  },
  {
    id: 22,
    pageId: "PGE-000022",
    name: "Event Gallery",
    description: "Photo and video gallery from school events including annual day, sports day, and cultural festivals.",
    status: "Published",
    tags: ["event", "fxvr"],
    collaborators: [
      { name: "Bilal Ahmad",   avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Hina Khan",     avatar: "https://i.pravatar.cc/150?img=17" },
    ],
    reader: "All Students",
    creator: { name: "Bilal Ahmad", avatar: "https://i.pravatar.cc/150?img=16" },
    createDate: "2024-11-01",
    updateDate: "2025-02-15",
    privacy: "Public",
  },
  {
    id: 23,
    pageId: "PGE-000023",
    name: "School History",
    description: "A historical overview of the school's founding, milestones, notable alumni, and institutional achievements.",
    status: "Published",
    tags: ["hjkl"],
    collaborators: [
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2" },
    ],
    reader: "General Public",
    creator: { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    createDate: "2024-08-05",
    updateDate: "2025-01-02",
    privacy: "Public",
  },
  {
    id: 24,
    pageId: "PGE-000024",
    name: "Vision Mission",
    description: "Official vision, mission, and core values statement guiding the school's educational philosophy.",
    status: "Published",
    tags: ["axmn", "policy"],
    collaborators: [
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    ],
    reader: "All",
    creator: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    createDate: "2024-07-15",
    updateDate: "2024-12-20",
    privacy: "Public",
  },
  {
    id: 25,
    pageId: "PGE-000025",
    name: "Notice Board Guide",
    description: "Instructions on how to post, read, and respond to official notices on the school notice board.",
    status: "Not Published",
    tags: ["guide", "vbhh"],
    collaborators: [
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Sana Tariq",    avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    reader: "",
    creator: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    createDate: "2025-02-10",
    updateDate: "2025-02-28",
    privacy: "Private",
  },
];

export default PAGES_DUMMY_DATA;
