export const noticeBoard = [
  {
    id: 1,
    title: "Exam Schedule Released",
    description: "The mid-term examination schedule for all classes has been released. Please check the timetable section in the portal.",
    date: "2025-12-20",
    category: "Academic",
    priority: "high",
    author: "Principal Office",
    content: "All students and parents are informed that the mid-term examination schedule has been released. The exams will be conducted from January 5 to January 15, 2026. Students should prepare accordingly.",
  },
  {
    id: 2,
    title: "Annual Sports Day - Registration Open",
    description: "Registration for the Annual Sports Day 2025 is now open. Participate in various events and win exciting prizes.",
    date: "2025-12-19",
    category: "Event",
    priority: "medium",
    author: "Sports Department",
    content: "Dear Students, The Annual Sports Day will be held on January 10, 2026. Registration is open until December 25, 2025. Various events including athletics, basketball, badminton, and cricket will be conducted. Limited spots available. Register now!",
  },
  {
    id: 3,
    title: "Winter Holiday Notice",
    description: "The school will remain closed from December 22, 2025 to January 2, 2026 for winter holidays. Classes will resume on January 3, 2026.",
    date: "2025-12-18",
    category: "Holiday",
    priority: "high",
    author: "Admin",
    content: "Winter holidays notice: School will be closed from December 22, 2025 to January 2, 2026. All offices will remain closed during this period. Classes will resume on January 3, 2026. Have a wonderful holiday!",
  },
  {
    id: 4,
    title: "New Library Hours",
    description: "The school library has extended its hours. Now open from 7:00 AM to 5:00 PM on weekdays.",
    date: "2025-12-17",
    category: "Facility",
    priority: "low",
    author: "Library",
    content: "Dear Students, The school library has extended its working hours effective from January 2026. New timings: Monday to Friday - 7:00 AM to 5:00 PM, Saturday - 8:00 AM to 2:00 PM. For any queries, contact the library staff.",
  },
  {
    id: 5,
    title: "Science Fair 2026 - Call for Entries",
    description: "All interested students are invited to participate in the Science Fair 2026. Submit your project proposals by January 10, 2026.",
    date: "2025-12-16",
    category: "Academic",
    priority: "medium",
    author: "Science Department",
    content: "The Science Fair 2026 is calling for entries from all students. Showcase your innovative science projects and ideas. Deadline for proposal submission: January 10, 2026. Winning projects will be displayed at the school annual exhibition.",
  },
  {
    id: 6,
    title: "Parent-Teacher Meeting Scheduled",
    description: "Parent-Teacher meetings will be held on January 8, 2026. Schedule your slot through the online portal.",
    date: "2025-12-15",
    category: "Meeting",
    priority: "high",
    author: "Admin",
    content: "All parents are requested to attend the Parent-Teacher meetings scheduled for January 8, 2026. Slots can be booked through the school portal. Discussions will focus on academic progress and overall development of students.",
  },
  {
    id: 7,
    title: "Scholarship Application Deadline",
    description: "The deadline for scholarship applications for the academic year 2026-27 is January 15, 2026.",
    date: "2025-12-14",
    category: "Announcement",
    priority: "high",
    author: "Finance",
    content: "Eligible students can apply for scholarships for the next academic year. The application deadline is January 15, 2026. All required documents must be submitted through the online portal. For eligibility criteria, visit the finance office.",
  },
  {
    id: 8,
    title: "Art Exhibition - Student Creations",
    description: "A special art exhibition featuring student artwork will be held next month. Students can showcase their talents.",
    date: "2025-12-13",
    category: "Event",
    priority: "low",
    author: "Art Department",
    content: "The Art Department is organizing a special exhibition to showcase student artwork. All students are encouraged to participate. Registration is free. Exhibition dates: January 20-25, 2026. Display your creativity!",
  },
  {
    id: 9,
    title: "Cafeteria Menu Update",
    description: "The cafeteria menu has been updated with new healthy options. Check the notice board for details.",
    date: "2025-12-12",
    category: "Facility",
    priority: "low",
    author: "Cafeteria",
    content: "Our cafeteria has introduced new healthy meal options including salads, smoothies, and nutritious snacks. Prices are competitive and affordable. We welcome your feedback on the new menu.",
  },
  {
    id: 10,
    title: "IT Lab - Computer Science Workshop",
    description: "A free workshop on Python programming will be conducted for interested students. Limited seats available.",
    date: "2025-12-11",
    category: "Workshop",
    priority: "medium",
    author: "IT Department",
    content: "The IT Department is conducting a free workshop on Python programming for beginners. Learn coding from basics to intermediate level. Date: January 6-7, 2026. Venue: Computer Lab. Register at the IT office. Limited to 30 participants.",
  },
];
