const studentClass = {
  studentId: "STD001",
  studentName: "Alice Brown",
  classId: "CLS001",
  className: "Class X-A",
  level: "10",
  section: "A",
  classTeacher: "Mr. Robert Smith",
  classroom: "Block-B, Room 201",
  timings: "08:00 AM - 2:00 PM",
};

const scheduleEvents = [
  {
    id: "EVT001",
    date: "2025-12-22",
    type: "class",
    subject: "Mathematics",
    time: "09:00 AM - 10:30 AM",
    teacher: "Dr. Sarah Johnson",
    room: "Block-B, Room 201",
    description: "Chapter 5 - Quadratic Equations",
  },
  {
    id: "EVT002",
    date: "2025-12-22",
    type: "exam",
    subject: "Physics",
    time: "11:00 AM - 12:30 PM",
    teacher: "Prof. John Smith",
    room: "Block-C, Exam Hall",
    description: "Mid-term Physics Exam",
  },
  {
    id: "EVT003",
    date: "2025-12-22",
    type: "break",
    subject: "Lunch Break",
    time: "12:30 PM - 01:15 PM",
    description: "Lunch & Recess",
  },
  {
    id: "EVT004",
    date: "2025-12-22",
    type: "class",
    subject: "English",
    time: "01:15 PM - 02:00 PM",
    teacher: "Ms. Lisa Anderson",
    room: "Block-A, Room 102",
    description: "Poetry Analysis",
  },
  {
    id: "EVT005",
    date: "2025-12-23",
    type: "class",
    subject: "Chemistry",
    time: "09:00 AM - 10:30 AM",
    teacher: "Dr. Emily Brown",
    room: "Lab-1",
    description: "Practical - Acid Base Reactions",
  },
  {
    id: "EVT006",
    date: "2025-12-23",
    type: "holiday",
    subject: "No Classes",
    description: "School Holiday",
  },
  {
    id: "EVT007",
    date: "2025-12-25",
    type: "class",
    subject: "History",
    time: "10:00 AM - 11:00 AM",
    teacher: "Prof. Robert Wilson",
    room: "Block-A, Room 201",
    description: "Indian Independence Movement",
  },
  {
    id: "EVT008",
    date: "2025-12-25",
    type: "assignment",
    subject: "Mathematics Assignment",
    dueDate: "2025-12-25",
    description: "Submit Exercise 5.1 to 5.5",
  },
  {
    id: "EVT009",
    date: "2025-12-27",
    type: "event",
    subject: "Sports Day",
    time: "03:00 PM onwards",
    description: "Annual Sports Day - All events at Sports Ground",
  },
  {
    id: "EVT010",
    date: "2025-12-29",
    type: "exam",
    subject: "Final Exam - Science",
    time: "09:00 AM - 12:00 PM",
    room: "Block-C, Exam Hall",
    description: "Final Science Examination",
  },
];

export { studentClass, scheduleEvents };
