const TASKS_DUMMY_DATA = [
  {
    id: 1,
    taskId: "TSK-000001",
    creatorName: "Ahmed Khan",
    creatorAvatar: "https://i.pravatar.cc/150?img=1",
    creatorRole: "Mathematics Teacher",
    subject: "Algebra Homework Assignment – Chapter 5",
    description:
      "Students are required to complete exercises 5.1 to 5.4 from the textbook. All work must be shown with proper step-by-step solutions. Submit in class on the due date.",
    type: "Homework",
    assignTo: [
      { name: "Ali Hassan", avatar: "https://i.pravatar.cc/150?img=10" },
      { name: "Sara Ahmed", avatar: "https://i.pravatar.cc/150?img=11" },
    ],
    observers: [{ name: "Dr. Rashid", avatar: "https://i.pravatar.cc/150?img=20" }],
    priority: "High",
    taskDate: { start: "2026-02-01", end: "2026-02-07" },
    completionPercentage: 75,
    status: "In Progress",
    defaultStatus: "Urgent",
    rating: 4,
    subTasks: 3,
    predecessor: null,
    createDate: "2026-01-25",
    updateDate: "2026-02-01",
    hasAttachment: true,
    attachmentType: "PDF",
  },
  {
    id: 2,
    taskId: "TSK-000002",
    creatorName: "Fatima Malik",
    creatorAvatar: "https://i.pravatar.cc/150?img=2",
    creatorRole: "Science Teacher",
    subject: "Science Project – Solar System Model",
    description:
      "Students must create a 3D model of the solar system. Label all planets with their names, distance from the sun, and key facts. Present your model to the class.",
    type: "Project",
    assignTo: [
      { name: "Zain Ul Abidin", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Maria Sheikh", avatar: "https://i.pravatar.cc/150?img=13" },
      { name: "Omar Farooq", avatar: "https://i.pravatar.cc/150?img=14" },
    ],
    observers: [
      { name: "Mrs. Nadia", avatar: "https://i.pravatar.cc/150?img=21" },
      { name: "Mr. Tariq", avatar: "https://i.pravatar.cc/150?img=22" },
    ],
    priority: "High",
    taskDate: { start: "2026-02-05", end: "2026-02-20" },
    completionPercentage: 40,
    status: "In Progress",
    defaultStatus: "Normal",
    rating: 3,
    subTasks: 5,
    predecessor: "TSK-000001",
    createDate: "2026-01-28",
    updateDate: "2026-02-05",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 3,
    taskId: "TSK-000003",
    creatorName: "Hassan Raza",
    creatorAvatar: "https://i.pravatar.cc/150?img=3",
    creatorRole: "English Teacher",
    subject: "Essay Writing – My School Experience",
    description:
      "Write a 500-word essay about your most memorable school experience. Focus on descriptive language and proper paragraph structure. Essays will be evaluated for creativity and grammar.",
    type: "Classwork",
    assignTo: [{ name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" }],
    observers: [],
    priority: "Medium",
    taskDate: { start: "2026-02-10", end: "2026-02-12" },
    completionPercentage: 100,
    status: "Completed",
    defaultStatus: "Default",
    rating: 5,
    subTasks: 0,
    predecessor: null,
    createDate: "2026-02-01",
    updateDate: "2026-02-12",
    hasAttachment: true,
    attachmentType: "Image",
  },
  {
    id: 4,
    taskId: "TSK-000004",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Administrator",
    subject: "Parent-Teacher Meeting – Grade 9",
    description:
      "Organize and schedule parent-teacher meetings for Grade 9 students. Prepare progress reports for each student. Coordinate with class teachers for timeslots.",
    type: "General",
    assignTo: [
      { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
      { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    observers: [{ name: "Principal", avatar: "https://i.pravatar.cc/150?img=25" }],
    priority: "High",
    taskDate: { start: "2026-02-15", end: "2026-02-16" },
    completionPercentage: 20,
    status: "Pending",
    defaultStatus: "Urgent",
    rating: 0,
    subTasks: 4,
    predecessor: null,
    createDate: "2026-02-08",
    updateDate: "2026-02-10",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 5,
    taskId: "TSK-000005",
    creatorName: "Nadia Iqbal",
    creatorAvatar: "https://i.pravatar.cc/150?img=5",
    creatorRole: "Grade 9 - A",
    subject: "Group Study Session – Chemistry Exam Prep",
    description:
      "Organize a group study session to prepare for the upcoming chemistry exam. Cover chapters 7 and 8 on chemical reactions and thermodynamics. Each group member should prepare topic notes.",
    type: "Group",
    assignTo: [
      { name: "Bilal Ahmad", avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Hina Khan", avatar: "https://i.pravatar.cc/150?img=17" },
      { name: "Usman Ali", avatar: "https://i.pravatar.cc/150?img=18" },
      { name: "Sana Tariq", avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    observers: [{ name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" }],
    priority: "Medium",
    taskDate: { start: "2026-02-18", end: "2026-02-18" },
    completionPercentage: 0,
    status: "Pending",
    defaultStatus: "Normal",
    rating: 0,
    subTasks: 2,
    predecessor: null,
    createDate: "2026-02-12",
    updateDate: "2026-02-12",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 6,
    taskId: "TSK-000006",
    creatorName: "Ahmed Khan",
    creatorAvatar: "https://i.pravatar.cc/150?img=1",
    creatorRole: "Mathematics Teacher",
    subject: "Geometry Classwork – Triangle Properties",
    description:
      "Complete in-class exercises on triangle properties including the Pythagorean theorem and angle sum property. Work in pairs to solve the 10 problems given on the worksheet.",
    type: "Classwork",
    assignTo: [
      { name: "Ali Hassan", avatar: "https://i.pravatar.cc/150?img=10" },
      { name: "Sara Ahmed", avatar: "https://i.pravatar.cc/150?img=11" },
    ],
    observers: [],
    priority: "Low",
    taskDate: { start: "2026-01-20", end: "2026-01-20" },
    completionPercentage: 100,
    status: "Completed",
    defaultStatus: "Default",
    rating: 4,
    subTasks: 0,
    predecessor: null,
    createDate: "2026-01-19",
    updateDate: "2026-01-20",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 7,
    taskId: "TSK-000007",
    creatorName: "Fatima Malik",
    creatorAvatar: "https://i.pravatar.cc/150?img=2",
    creatorRole: "Science Teacher",
    subject: "Lab Report – Photosynthesis Experiment",
    description:
      "Write a detailed lab report for the photosynthesis experiment conducted last week. Include hypothesis, materials, procedure, observations, and conclusions. Attach a diagram of the setup.",
    type: "Homework",
    assignTo: [{ name: "Zain Ul Abidin", avatar: "https://i.pravatar.cc/150?img=12" }],
    observers: [{ name: "Mrs. Nadia", avatar: "https://i.pravatar.cc/150?img=21" }],
    priority: "High",
    taskDate: { start: "2026-01-15", end: "2026-01-22" },
    completionPercentage: 100,
    status: "Over Due",
    defaultStatus: "Urgent",
    rating: 2,
    subTasks: 1,
    predecessor: "TSK-000002",
    createDate: "2026-01-14",
    updateDate: "2026-01-23",
    hasAttachment: true,
    attachmentType: "PDF",
  },
  {
    id: 8,
    taskId: "TSK-000008",
    creatorName: "Hassan Raza",
    creatorAvatar: "https://i.pravatar.cc/150?img=3",
    creatorRole: "English Teacher",
    subject: "Book Review – To Kill a Mockingbird",
    description:
      "Read the assigned novel and write a comprehensive book review covering plot summary, themes, character analysis, and personal opinion. Minimum 800 words required.",
    type: "Homework",
    assignTo: [
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Omar Farooq", avatar: "https://i.pravatar.cc/150?img=14" },
    ],
    observers: [],
    priority: "Medium",
    taskDate: { start: "2026-02-01", end: "2026-02-28" },
    completionPercentage: 30,
    status: "In Progress",
    defaultStatus: "Normal",
    rating: 3,
    subTasks: 2,
    predecessor: "TSK-000003",
    createDate: "2026-01-30",
    updateDate: "2026-02-10",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 9,
    taskId: "TSK-000009",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Administrator",
    subject: "Annual Sports Day Planning",
    description:
      "Coordinate annual sports day event including venue setup, sports event schedule, participant registration, and prize distribution. Assign responsibilities to PE teachers and student council.",
    type: "General",
    assignTo: [
      { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    ],
    observers: [
      { name: "Principal", avatar: "https://i.pravatar.cc/150?img=25" },
      { name: "Vice Principal", avatar: "https://i.pravatar.cc/150?img=26" },
    ],
    priority: "Medium",
    taskDate: { start: "2026-03-01", end: "2026-03-15" },
    completionPercentage: 10,
    status: "Pending",
    defaultStatus: "Normal",
    rating: 0,
    subTasks: 5,
    predecessor: null,
    createDate: "2026-02-20",
    updateDate: "2026-02-20",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 10,
    taskId: "TSK-000010",
    creatorName: "Tariq Mahmood",
    creatorAvatar: "https://i.pravatar.cc/150?img=6",
    creatorRole: "Mathematics Teacher",
    subject: "Lesson Plan – Calculus Unit 3",
    description:
      "Prepare a detailed lesson plan for Calculus Unit 3 covering derivatives and integration. Include learning objectives, teaching methodology, examples, and assessment strategy.",
    type: "General",
    assignTo: [{ name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" }],
    observers: [{ name: "Dr. Rashid", avatar: "https://i.pravatar.cc/150?img=20" }],
    priority: "High",
    taskDate: { start: "2026-02-10", end: "2026-02-14" },
    completionPercentage: 60,
    status: "In Progress",
    defaultStatus: "Urgent",
    rating: 4,
    subTasks: 3,
    predecessor: null,
    createDate: "2026-02-05",
    updateDate: "2026-02-12",
    hasAttachment: true,
    attachmentType: "PDF",
  },
  {
    id: 11,
    taskId: "TSK-000011",
    creatorName: "Nadia Iqbal",
    creatorAvatar: "https://i.pravatar.cc/150?img=5",
    creatorRole: "Grade 9 - A",
    subject: "Physics Group Project – Renewable Energy",
    description:
      "Research and prepare a group presentation on renewable energy sources. Cover solar, wind, hydro, and geothermal energy. Include cost analysis and environmental impact comparison.",
    type: "Project",
    assignTo: [
      { name: "Bilal Ahmad", avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Hina Khan", avatar: "https://i.pravatar.cc/150?img=17" },
      { name: "Usman Ali", avatar: "https://i.pravatar.cc/150?img=18" },
    ],
    observers: [{ name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" }],
    priority: "High",
    taskDate: { start: "2026-01-10", end: "2026-01-31" },
    completionPercentage: 100,
    status: "Over Due",
    defaultStatus: "Urgent",
    rating: 3,
    subTasks: 4,
    predecessor: "TSK-000005",
    createDate: "2026-01-08",
    updateDate: "2026-02-01",
    hasAttachment: true,
    attachmentType: "PDF",
  },
  {
    id: 12,
    taskId: "TSK-000012",
    creatorName: "Ahmed Khan",
    creatorAvatar: "https://i.pravatar.cc/150?img=1",
    creatorRole: "Mathematics Teacher",
    subject: "Statistics Homework – Data Collection Survey",
    description:
      "Conduct a simple survey collecting data on at least 30 respondents. Organize data in frequency tables and calculate mean, median, and mode. Present with graphs.",
    type: "Homework",
    assignTo: [
      { name: "Ali Hassan", avatar: "https://i.pravatar.cc/150?img=10" },
      { name: "Sara Ahmed", avatar: "https://i.pravatar.cc/150?img=11" },
      { name: "Maria Sheikh", avatar: "https://i.pravatar.cc/150?img=13" },
    ],
    observers: [],
    priority: "Medium",
    taskDate: { start: "2026-02-20", end: "2026-02-27" },
    completionPercentage: 0,
    status: "Pending",
    defaultStatus: "Normal",
    rating: 0,
    subTasks: 2,
    predecessor: "TSK-000006",
    createDate: "2026-02-15",
    updateDate: "2026-02-15",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 13,
    taskId: "TSK-000013",
    creatorName: "Fatima Malik",
    creatorAvatar: "https://i.pravatar.cc/150?img=2",
    creatorRole: "Science Teacher",
    subject: "Biology Classwork – Cell Division Diagrams",
    description:
      "Draw and label detailed diagrams of mitosis and meiosis cell division processes. Include all phases with proper annotations. Use colored pencils for clear differentiation.",
    type: "Classwork",
    assignTo: [
      { name: "Zain Ul Abidin", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Sana Tariq", avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    observers: [],
    priority: "Low",
    taskDate: { start: "2026-02-25", end: "2026-02-25" },
    completionPercentage: 0,
    status: "Pending",
    defaultStatus: "Default",
    rating: 0,
    subTasks: 0,
    predecessor: null,
    createDate: "2026-02-20",
    updateDate: "2026-02-20",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 14,
    taskId: "TSK-000014",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Administrator",
    subject: "Exam Timetable Preparation – Mid Term",
    description:
      "Prepare the mid-term examination timetable for all grades. Coordinate with subject teachers for preferred dates, avoid clashes, and distribute timetable to all students and staff.",
    type: "General",
    assignTo: [
      { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    ],
    observers: [{ name: "Principal", avatar: "https://i.pravatar.cc/150?img=25" }],
    priority: "High",
    taskDate: { start: "2026-01-05", end: "2026-01-15" },
    completionPercentage: 100,
    status: "Completed",
    defaultStatus: "Urgent",
    rating: 5,
    subTasks: 3,
    predecessor: null,
    createDate: "2026-01-01",
    updateDate: "2026-01-15",
    hasAttachment: true,
    attachmentType: "PDF",
  },
  {
    id: 15,
    taskId: "TSK-000015",
    creatorName: "Hassan Raza",
    creatorAvatar: "https://i.pravatar.cc/150?img=3",
    creatorRole: "English Teacher",
    subject: "Grammar Drills – Tenses Practice",
    description:
      "Complete the tenses practice worksheet covering present perfect, past continuous, and future perfect tenses. Write three original sentences using each tense form.",
    type: "Classwork",
    assignTo: [
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Omar Farooq", avatar: "https://i.pravatar.cc/150?img=14" },
    ],
    observers: [],
    priority: "Low",
    taskDate: { start: "2026-02-28", end: "2026-02-28" },
    completionPercentage: 0,
    status: "Pending",
    defaultStatus: "Default",
    rating: 0,
    subTasks: 0,
    predecessor: null,
    createDate: "2026-02-25",
    updateDate: "2026-02-25",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 16,
    taskId: "TSK-000016",
    creatorName: "Tariq Mahmood",
    creatorAvatar: "https://i.pravatar.cc/150?img=6",
    creatorRole: "Mathematics Teacher",
    subject: "Grade 9 Math Test – Chapter 3 Review",
    description:
      "Prepare students for upcoming chapter test by reviewing all key concepts from Chapter 3 on quadratic equations. Provide practice problems and model solutions.",
    type: "General",
    assignTo: [
      { name: "Ali Hassan", avatar: "https://i.pravatar.cc/150?img=10" },
      { name: "Sara Ahmed", avatar: "https://i.pravatar.cc/150?img=11" },
      { name: "Maria Sheikh", avatar: "https://i.pravatar.cc/150?img=13" },
    ],
    observers: [{ name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" }],
    priority: "High",
    taskDate: { start: "2026-01-25", end: "2026-01-28" },
    completionPercentage: 100,
    status: "Completed",
    defaultStatus: "Default",
    rating: 4,
    subTasks: 2,
    predecessor: null,
    createDate: "2026-01-20",
    updateDate: "2026-01-28",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 17,
    taskId: "TSK-000017",
    creatorName: "Nadia Iqbal",
    creatorAvatar: "https://i.pravatar.cc/150?img=5",
    creatorRole: "Grade 9 - A",
    subject: "Student Council Meeting – Event Planning",
    description:
      "Organize and conduct student council meeting to plan upcoming school events including science fair, inter-school debate competition, and graduation ceremony activities.",
    type: "Group",
    assignTo: [
      { name: "Bilal Ahmad", avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Hina Khan", avatar: "https://i.pravatar.cc/150?img=17" },
    ],
    observers: [{ name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" }],
    priority: "Medium",
    taskDate: { start: "2026-02-22", end: "2026-02-22" },
    completionPercentage: 50,
    status: "In Progress",
    defaultStatus: "Normal",
    rating: 3,
    subTasks: 1,
    predecessor: null,
    createDate: "2026-02-18",
    updateDate: "2026-02-22",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 18,
    taskId: "TSK-000018",
    creatorName: "Fatima Malik",
    creatorAvatar: "https://i.pravatar.cc/150?img=2",
    creatorRole: "Science Teacher",
    subject: "Chemistry Assignment – Periodic Table Elements",
    description:
      "Research 5 elements from the periodic table. For each element, write about its discovery, properties, uses in daily life, and interesting facts. Present findings in a 2-page report.",
    type: "Homework",
    assignTo: [
      { name: "Zain Ul Abidin", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Maria Sheikh", avatar: "https://i.pravatar.cc/150?img=13" },
    ],
    observers: [],
    priority: "Medium",
    taskDate: { start: "2026-01-28", end: "2026-02-04" },
    completionPercentage: 100,
    status: "Completed",
    defaultStatus: "Normal",
    rating: 4,
    subTasks: 1,
    predecessor: null,
    createDate: "2026-01-22",
    updateDate: "2026-02-04",
    hasAttachment: true,
    attachmentType: "Image",
  },
  {
    id: 19,
    taskId: "TSK-000019",
    creatorName: "Ahmed Khan",
    creatorAvatar: "https://i.pravatar.cc/150?img=1",
    creatorRole: "Mathematics Teacher",
    subject: "Probability Homework – Coin and Dice Experiments",
    description:
      "Perform 50 trials each for coin flip and dice roll experiments. Record results in a table, calculate experimental probability, and compare with theoretical probability.",
    type: "Homework",
    assignTo: [{ name: "Ali Hassan", avatar: "https://i.pravatar.cc/150?img=10" }],
    observers: [],
    priority: "Low",
    taskDate: { start: "2026-01-08", end: "2026-01-14" },
    completionPercentage: 100,
    status: "Over Due",
    defaultStatus: "Default",
    rating: 2,
    subTasks: 0,
    predecessor: null,
    createDate: "2026-01-06",
    updateDate: "2026-01-15",
    hasAttachment: false,
    attachmentType: null,
  },
  {
    id: 20,
    taskId: "TSK-000020",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Administrator",
    subject: "Staff Training Workshop – Digital Tools in Education",
    description:
      "Arrange a professional development workshop for all teaching staff on using digital tools and e-learning platforms. Cover Google Classroom, Zoom, and interactive presentation tools.",
    type: "General",
    assignTo: [
      { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
      { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    ],
    observers: [{ name: "Principal", avatar: "https://i.pravatar.cc/150?img=25" }],
    priority: "Medium",
    taskDate: { start: "2026-03-05", end: "2026-03-06" },
    completionPercentage: 0,
    status: "Pending",
    defaultStatus: "Normal",
    rating: 0,
    subTasks: 3,
    predecessor: null,
    createDate: "2026-02-25",
    updateDate: "2026-02-25",
    hasAttachment: false,
    attachmentType: null,
  },
];

export default TASKS_DUMMY_DATA;
