const LEAVES_DUMMY_DATA = [
  {
    id: 1,
    leaveId: "LEV-000121",
    applicantName: "Ahmed Khan",
    applicantAvatar: null,
    applicantRole: "Mathematics Teacher",
    leaveFor: "teacher",
    leaveType: "Sick Leave",
    startDate: "2025-01-15",
    endDate: "2025-01-17",
    days: 3,
    description:
      "I am suffering from high fever and need medical rest. Doctor has advised complete bed rest for 3 days to prevent further complications.",
    status: "approved",
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "approved",
        comment: "Approved. Please take care and recover soon.",
      },
    ],
    hasAttachment: true,
    attachmentType: "pdf",
    createdAt: "2025-01-14",
    updatedAt: "2025-01-14",
  },
  {
    id: 2,
    leaveId: "LEV-000122",
    applicantName: "Sara Ali",
    applicantAvatar: null,
    applicantRole: "Grade 9 - A",
    leaveFor: "student",
    leaveType: "Family Emergency",
    startDate: "2025-01-20",
    endDate: "2025-01-21",
    days: 2,
    description:
      "A close family member was hospitalized and I need to travel to another city to be with them during this difficult time.",
    status: "approved",
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: null,
        response: "approved",
        comment: "Approved. Hope everything goes well.",
      },
      {
        id: 2,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "approved",
        comment: "Approved.",
      },
    ],
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-01-19",
    updatedAt: "2025-01-19",
  },
  {
    id: 3,
    leaveId: "LEV-000123",
    applicantName: "Muhammad Bilal",
    applicantAvatar: null,
    applicantRole: "Science Teacher",
    leaveFor: "teacher",
    leaveType: "Annual Leave",
    startDate: "2025-02-03",
    endDate: "2025-02-07",
    days: 5,
    description:
      "I would like to take annual leave for a family trip that has been planned for several months. Lesson plans will be handed over to the substitute teacher.",
    status: "in-process",
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "approved",
        comment: "Approved by Principal.",
      },
      {
        id: 2,
        name: "Mr. Tariq Rehman",
        role: "HR Manager",
        avatar: null,
        response: "pending",
        comment: "",
      },
    ],
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-01-28",
    updatedAt: "2025-01-28",
  },
  {
    id: 4,
    leaveId: "LEV-000124",
    applicantName: "Fatima Sheikh",
    applicantAvatar: null,
    applicantRole: "Grade 10 - B",
    leaveFor: "student",
    leaveType: "Medical Leave",
    startDate: "2025-01-22",
    endDate: "2025-01-24",
    days: 3,
    description:
      "Scheduled dental surgery requires 3 days of rest post-operation. Medical certificate attached.",
    status: "approved",
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: null,
        response: "approved",
        comment: "Approved with medical certificate.",
      },
    ],
    hasAttachment: true,
    attachmentType: "jpg",
    createdAt: "2025-01-21",
    updatedAt: "2025-01-21",
  },
  {
    id: 5,
    leaveId: "LEV-000125",
    applicantName: "Omar Farooq",
    applicantAvatar: null,
    applicantRole: "English Teacher",
    leaveFor: "teacher",
    leaveType: "Casual Leave",
    startDate: "2025-02-10",
    endDate: "2025-02-10",
    days: 1,
    description:
      "Personal errand that requires my presence at a government office for documentation purposes.",
    status: "pending",
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "pending",
        comment: "",
      },
    ],
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-02-07",
    updatedAt: "2025-02-07",
  },
  {
    id: 6,
    leaveId: "LEV-000126",
    applicantName: "Ayesha Malik",
    applicantAvatar: null,
    applicantRole: "Grade 11 - A",
    leaveFor: "student",
    leaveType: "Exam Leave",
    startDate: "2025-02-12",
    endDate: "2025-02-14",
    days: 3,
    description:
      "Appearing in external competitive exams conducted by the Board of Intermediate and Secondary Education.",
    status: "approved",
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: null,
        response: "approved",
        comment: "Best of luck!",
      },
      {
        id: 2,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "approved",
        comment: "Approved.",
      },
    ],
    hasAttachment: true,
    attachmentType: "pdf",
    createdAt: "2025-02-08",
    updatedAt: "2025-02-08",
  },
  {
    id: 7,
    leaveId: "LEV-000127",
    applicantName: "Hassan Raza",
    applicantAvatar: null,
    applicantRole: "Computer Science Teacher",
    leaveFor: "teacher",
    leaveType: "Sick Leave",
    startDate: "2025-01-08",
    endDate: "2025-01-09",
    days: 2,
    description:
      "Severe migraine attack. Unable to conduct classes. Will be available remotely for urgent queries.",
    status: "declined",
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "declined",
        comment: "Substitute already unavailable. Please arrange a substitute or reconsider dates.",
      },
    ],
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-01-07",
    updatedAt: "2025-01-07",
  },
  {
    id: 8,
    leaveId: "LEV-000128",
    applicantName: "Nadia Rahman",
    applicantAvatar: null,
    applicantRole: "Grade 9 - B",
    leaveFor: "student",
    leaveType: "Family Emergency",
    startDate: "2025-01-28",
    endDate: "2025-01-29",
    days: 2,
    description:
      "Attending a family bereavement. Lost a close relative and need to participate in funeral rites.",
    status: "approved",
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: null,
        response: "approved",
        comment: "Our condolences. Approved.",
      },
    ],
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-01-27",
    updatedAt: "2025-01-27",
  },
  {
    id: 9,
    leaveId: "LEV-000129",
    applicantName: "Usman Tariq",
    applicantAvatar: null,
    applicantRole: "Physics Teacher",
    leaveFor: "teacher",
    leaveType: "Annual Leave",
    startDate: "2025-02-17",
    endDate: "2025-02-21",
    days: 5,
    description:
      "Annual leave for personal travel. All lesson plans have been submitted to the department head.",
    status: "pending",
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "pending",
        comment: "",
      },
      {
        id: 2,
        name: "Mr. Tariq Rehman",
        role: "HR Manager",
        avatar: null,
        response: "pending",
        comment: "",
      },
    ],
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-02-10",
    updatedAt: "2025-02-10",
  },
  {
    id: 10,
    leaveId: "LEV-000130",
    applicantName: "Zara Hussain",
    applicantAvatar: null,
    applicantRole: "Grade 8 - A",
    leaveFor: "student",
    leaveType: "Medical Leave",
    startDate: "2025-01-13",
    endDate: "2025-01-15",
    days: 3,
    description:
      "Recovering from appendix surgery. Doctor has recommended full rest for at least one week.",
    status: "approved",
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: null,
        response: "approved",
        comment: "Approved. Speedy recovery!",
      },
      {
        id: 2,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "approved",
        comment: "Approved.",
      },
    ],
    hasAttachment: true,
    attachmentType: "pdf",
    createdAt: "2025-01-12",
    updatedAt: "2025-01-12",
  },
  {
    id: 11,
    leaveId: "LEV-000131",
    applicantName: "Bilal Niazi",
    applicantAvatar: null,
    applicantRole: "Chemistry Teacher",
    leaveFor: "teacher",
    leaveType: "Casual Leave",
    startDate: "2025-02-05",
    endDate: "2025-02-05",
    days: 1,
    description: "Attending a professional development workshop on modern teaching methodologies.",
    status: "approved",
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "approved",
        comment: "Great initiative. Approved.",
      },
    ],
    hasAttachment: true,
    attachmentType: "pdf",
    createdAt: "2025-02-03",
    updatedAt: "2025-02-03",
  },
  {
    id: 12,
    leaveId: "LEV-000132",
    applicantName: "Amna Siddiqui",
    applicantAvatar: null,
    applicantRole: "Grade 10 - A",
    leaveFor: "student",
    leaveType: "Sick Leave",
    startDate: "2025-01-30",
    endDate: "2025-01-31",
    days: 2,
    description:
      "Down with food poisoning. Currently under medication and not in a condition to attend school.",
    status: "in-process",
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: null,
        response: "approved",
        comment: "Approved by class teacher.",
      },
      {
        id: 2,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "pending",
        comment: "",
      },
    ],
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-01-29",
    updatedAt: "2025-01-29",
  },
  {
    id: 13,
    leaveId: "LEV-000133",
    applicantName: "Mariam Khan",
    applicantAvatar: null,
    applicantRole: "Biology Teacher",
    leaveFor: "teacher",
    leaveType: "Maternity Leave",
    startDate: "2025-03-01",
    endDate: "2025-05-31",
    days: 90,
    description:
      "Applying for maternity leave as per school policy. All handover documents will be submitted to the department head before the leave period begins.",
    status: "approved",
    approvers: [
      {
        id: 1,
        name: "Mr. Tariq Rehman",
        role: "HR Manager",
        avatar: null,
        response: "approved",
        comment: "Approved as per maternity policy.",
      },
      {
        id: 2,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "approved",
        comment: "Approved. Wishing you all the best!",
      },
    ],
    hasAttachment: true,
    attachmentType: "pdf",
    createdAt: "2025-02-01",
    updatedAt: "2025-02-01",
  },
  {
    id: 14,
    leaveId: "LEV-000134",
    applicantName: "Faisal Ahmed",
    applicantAvatar: null,
    applicantRole: "Grade 11 - B",
    leaveFor: "student",
    leaveType: "Casual Leave",
    startDate: "2025-02-06",
    endDate: "2025-02-06",
    days: 1,
    description:
      "Participating in an inter-school debate competition representing our school.",
    status: "approved",
    approvers: [
      {
        id: 1,
        name: "Mrs. Ayesha Noor",
        role: "Class Teacher",
        avatar: null,
        response: "approved",
        comment: "Great representation. Approved!",
      },
    ],
    hasAttachment: true,
    attachmentType: "jpg",
    createdAt: "2025-02-04",
    updatedAt: "2025-02-04",
  },
  {
    id: 15,
    leaveId: "LEV-000135",
    applicantName: "Sadia Iqbal",
    applicantAvatar: null,
    applicantRole: "Urdu Teacher",
    leaveFor: "teacher",
    leaveType: "Sick Leave",
    startDate: "2025-02-18",
    endDate: "2025-02-19",
    days: 2,
    description:
      "Suffering from severe back pain that makes it impossible to stand for extended periods. Physiotherapy sessions scheduled.",
    status: "declined",
    approvers: [
      {
        id: 1,
        name: "Dr. Sana Malik",
        role: "Principal",
        avatar: null,
        response: "declined",
        comment: "Annual day rehearsals are scheduled. Please reconsider or arrange a substitute.",
      },
    ],
    hasAttachment: false,
    attachmentType: null,
    createdAt: "2025-02-15",
    updatedAt: "2025-02-15",
  },
];

export default LEAVES_DUMMY_DATA;
