const courses = [
  {
    id: "CRS001",
    name: "Mathematics",
    code: "MATH101",
    instructor: "Dr. Sarah Johnson",
    grade: "A",
    progress: 85,
    status: "Active",
    credits: 4,
    semester: "Fall 2024",
    startDate: "15 Aug 2024",
    endDate: "15 Dec 2024",
    description: "Advanced Mathematics course covering calculus and algebra",
  },
  {
    id: "CRS002",
    name: "Physics",
    code: "PHY101",
    instructor: "Prof. John Smith",
    grade: "B+",
    progress: 72,
    status: "Active",
    credits: 3,
    semester: "Fall 2024",
    startDate: "15 Aug 2024",
    endDate: "15 Dec 2024",
    description: "Fundamental principles of physics and mechanics",
  },
  {
    id: "CRS003",
    name: "Chemistry",
    code: "CHM101",
    instructor: "Dr. Emily Brown",
    grade: "A-",
    progress: 88,
    status: "Active",
    credits: 3,
    semester: "Fall 2024",
    startDate: "15 Aug 2024",
    endDate: "15 Dec 2024",
    description: "Organic and inorganic chemistry fundamentals",
  },
  {
    id: "CRS004",
    name: "English Literature",
    code: "ENG101",
    instructor: "Ms. Lisa Anderson",
    grade: "A",
    progress: 90,
    status: "Completed",
    credits: 3,
    semester: "Summer 2024",
    startDate: "01 Jun 2024",
    endDate: "31 Aug 2024",
    description: "Analysis of contemporary and classical literature",
  },
  {
    id: "CRS005",
    name: "Computer Science",
    code: "CS101",
    instructor: "Dr. Michael Davis",
    grade: "A+",
    progress: 95,
    status: "Active",
    credits: 4,
    semester: "Fall 2024",
    startDate: "15 Aug 2024",
    endDate: "15 Dec 2024",
    description: "Introduction to programming and data structures",
  },
  {
    id: "CRS006",
    name: "History",
    code: "HIST101",
    instructor: "Prof. Robert Wilson",
    grade: "B",
    progress: 68,
    status: "Active",
    credits: 2,
    semester: "Fall 2024",
    startDate: "15 Aug 2024",
    endDate: "15 Dec 2024",
    description: "World history from medieval times to modern era",
  },
  {
    id: "CRS007",
    name: "Biology",
    code: "BIO101",
    instructor: "Dr. Amanda Martinez",
    grade: "A-",
    progress: 86,
    status: "Active",
    credits: 3,
    semester: "Fall 2024",
    startDate: "15 Aug 2024",
    endDate: "15 Dec 2024",
    description: "Cell biology and genetics fundamentals",
  },
  {
    id: "CRS008",
    name: "Economics",
    code: "ECON101",
    instructor: "Prof. David Miller",
    grade: "B+",
    progress: 74,
    status: "Completed",
    credits: 3,
    semester: "Spring 2024",
    startDate: "01 Feb 2024",
    endDate: "30 Apr 2024",
    description: "Principles of microeconomics and macroeconomics",
  },
];

export default courses;
