const PROJECTS_DUMMY_DATA = [
  {
    id: 1,
    projectId: "PRJ-000001",
    name: "Science Fair 2025",
    code: "SF25",
    coverImage: "https://picsum.photos/seed/ScienceFair2025/400/200",
    adminUser: { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    users: [
      { name: "Ahmed Khan",  avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    ],
    category: "Active",
    description:
      "Annual science fair showcasing student experiments and innovations. Students from Grade 8–10 will present their projects to a panel of judges. Prizes awarded for top three projects.",
    date: { start: "2025-03-01", end: "2025-03-15" },
    status: "Active",
    isStarred: true,
    createdAt: "2025-01-10",
    updatedAt: "2025-02-20",
  },
  {
    id: 2,
    projectId: "PRJ-000002",
    name: "Annual Sports Day",
    code: "ASD",
    coverImage: "https://picsum.photos/seed/AnnualSportsDay/400/200",
    adminUser: { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    users: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5" },
    ],
    category: "Active",
    description:
      "Annual inter-house sports competition covering athletics, cricket, football, and badminton. Coordination with PE department for scheduling and venue setup. Medals and trophies to be arranged.",
    date: { start: "2025-02-20", end: "2025-02-22" },
    status: "Active",
    isStarred: false,
    createdAt: "2025-01-15",
    updatedAt: "2025-02-18",
  },
  {
    id: 3,
    projectId: "PRJ-000003",
    name: "Math Olympiad",
    code: "MO25",
    coverImage: "https://picsum.photos/seed/MathOlympiad/400/200",
    adminUser: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    users: [
      { name: "Ahmed Khan",  avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    category: "Completed",
    description:
      "Inter-school mathematics competition for Grade 9 and 10 students. Topics include algebra, geometry, and number theory. Selected students will represent the school at district level.",
    date: { start: "2025-01-05", end: "2025-01-20" },
    status: "Completed",
    isStarred: true,
    createdAt: "2024-12-01",
    updatedAt: "2025-01-21",
  },
  {
    id: 4,
    projectId: "PRJ-000004",
    name: "Art Exhibition",
    code: "ARTX",
    coverImage: "https://picsum.photos/seed/ArtExhibition/400/200",
    adminUser: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    users: [
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2" },
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
    ],
    category: "On Hold",
    description:
      "Student art exhibition displaying paintings, sculptures, and digital artwork. Open to parents and the public for one weekend. Artwork will be judged and awarded in multiple categories.",
    date: { start: "2025-04-10", end: "2025-04-12" },
    status: "On Hold",
    isStarred: false,
    createdAt: "2025-02-01",
    updatedAt: "2025-02-15",
  },
  {
    id: 5,
    projectId: "PRJ-000005",
    name: "School Magazine",
    code: "SMAG",
    coverImage: "https://picsum.photos/seed/SchoolMagazine/400/200",
    adminUser: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    users: [
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Omar Farooq",     avatar: "https://i.pravatar.cc/150?img=14" },
    ],
    category: "Active",
    description:
      "Bi-annual school magazine featuring student articles, poetry, sports news, and creative writing. Students from the editorial club will manage content creation and layout design.",
    date: { start: "2025-02-01", end: "2025-03-31" },
    status: "Active",
    isStarred: false,
    createdAt: "2025-01-20",
    updatedAt: "2025-02-22",
  },
  {
    id: 6,
    projectId: "PRJ-000006",
    name: "Drama Club Production",
    code: "DCP",
    coverImage: "https://picsum.photos/seed/DramaClubProduction/400/200",
    adminUser: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    users: [
      { name: "Bilal Ahmad",    avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Hina Khan",      avatar: "https://i.pravatar.cc/150?img=17" },
      { name: "Sana Tariq",     avatar: "https://i.pravatar.cc/150?img=19" },
    ],
    category: "On Hold",
    description:
      "Annual school drama production featuring original student-written scripts. Rehearsals to run for six weeks. Stage decoration, costumes, and sound arrangements are part of the project.",
    date: { start: "2025-05-01", end: "2025-05-20" },
    status: "On Hold",
    isStarred: true,
    createdAt: "2025-02-10",
    updatedAt: "2025-02-25",
  },
  {
    id: 7,
    projectId: "PRJ-000007",
    name: "Environmental Drive",
    code: "ENV",
    coverImage: "https://picsum.photos/seed/EnvironmentalDrive/400/200",
    adminUser: { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    users: [
      { name: "Zain Ul Abidin", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Maria Sheikh",   avatar: "https://i.pravatar.cc/150?img=13" },
    ],
    category: "Completed",
    description:
      "School-wide tree plantation and recycling campaign. Students will plant 200 trees in the school grounds and surrounding neighborhood. Awareness sessions on climate change included.",
    date: { start: "2024-11-01", end: "2024-11-30" },
    status: "Completed",
    isStarred: false,
    createdAt: "2024-10-01",
    updatedAt: "2024-12-01",
  },
  {
    id: 8,
    projectId: "PRJ-000008",
    name: "Tech Innovation Fair",
    code: "TIF",
    coverImage: "https://picsum.photos/seed/TechInnovationFair/400/200",
    adminUser: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    users: [
      { name: "Ahmed Khan",     avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Bilal Ahmad",    avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Usman Ali",      avatar: "https://i.pravatar.cc/150?img=18" },
    ],
    category: "Active",
    description:
      "Technology and innovation showcase for students interested in robotics, coding, and AI projects. Guest speakers from the tech industry will judge and mentor participants.",
    date: { start: "2025-03-20", end: "2025-03-22" },
    status: "Active",
    isStarred: true,
    createdAt: "2025-01-25",
    updatedAt: "2025-02-20",
  },
  {
    id: 9,
    projectId: "PRJ-000009",
    name: "Cultural Festival",
    code: "CULT",
    coverImage: "https://picsum.photos/seed/CulturalFestival/400/200",
    adminUser: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    users: [
      { name: "Hina Khan",       avatar: "https://i.pravatar.cc/150?img=17" },
      { name: "Sana Tariq",      avatar: "https://i.pravatar.cc/150?img=19" },
      { name: "Maria Sheikh",    avatar: "https://i.pravatar.cc/150?img=13" },
    ],
    category: "Associate",
    description:
      "Multi-cultural festival celebrating diversity among students. Events include traditional dances, food stalls, cultural exhibitions, and music performances from different regions.",
    date: { start: "2025-06-05", end: "2025-06-06" },
    status: "Associate",
    isStarred: false,
    createdAt: "2025-02-18",
    updatedAt: "2025-02-28",
  },
  {
    id: 10,
    projectId: "PRJ-000010",
    name: "Library Renovation",
    code: "LIBR",
    coverImage: "https://picsum.photos/seed/LibraryRenovation/400/200",
    adminUser: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    users: [
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2" },
    ],
    category: "On Hold",
    description:
      "Complete renovation of the school library including new shelving, reading corners, digital catalog system, and a dedicated e-learning zone. Budget approved pending vendor selection.",
    date: { start: "2025-04-01", end: "2025-07-31" },
    status: "On Hold",
    isStarred: false,
    createdAt: "2025-02-05",
    updatedAt: "2025-02-20",
  },
  {
    id: 11,
    projectId: "PRJ-000011",
    name: "School Website Redesign",
    code: "WEBD",
    coverImage: "https://picsum.photos/seed/SchoolWebsiteRedesign/400/200",
    adminUser: { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    users: [
      { name: "Usman Ali",  avatar: "https://i.pravatar.cc/150?img=18" },
      { name: "Bilal Ahmad", avatar: "https://i.pravatar.cc/150?img=16" },
    ],
    category: "Active",
    description:
      "Complete redesign of the school's official website with modern UI, news feed, event calendar, and parent portal integration. Mobile-responsive design using latest web technologies.",
    date: { start: "2025-02-01", end: "2025-04-30" },
    status: "Active",
    isStarred: true,
    createdAt: "2025-01-15",
    updatedAt: "2025-02-25",
  },
  {
    id: 12,
    projectId: "PRJ-000012",
    name: "Parent Teacher Portal",
    code: "PTP",
    coverImage: "https://picsum.photos/seed/ParentTeacherPortal/400/200",
    adminUser: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    users: [
      { name: "Ahmed Khan",    avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2" },
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
    ],
    category: "Completed",
    description:
      "Digital portal allowing parents to track attendance, grades, assignments, and communicate directly with teachers. Integrated with the school management system.",
    date: { start: "2024-09-01", end: "2024-12-31" },
    status: "Completed",
    isStarred: false,
    createdAt: "2024-08-15",
    updatedAt: "2025-01-02",
  },
  {
    id: 13,
    projectId: "PRJ-000013",
    name: "Smart Classroom Setup",
    code: "SCS",
    coverImage: "https://picsum.photos/seed/SmartClassroomSetup/400/200",
    adminUser: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    users: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    category: "Associate",
    description:
      "Installation of smart boards, projectors, and Wi-Fi infrastructure across all Grade 9 and 10 classrooms. Teacher training on digital tools included as part of the rollout.",
    date: { start: "2025-07-01", end: "2025-08-31" },
    status: "Associate",
    isStarred: false,
    createdAt: "2025-02-22",
    updatedAt: "2025-02-28",
  },
  {
    id: 14,
    projectId: "PRJ-000014",
    name: "Student Council Elections",
    code: "SCE",
    coverImage: "https://picsum.photos/seed/StudentCouncilElections/400/200",
    adminUser: { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    users: [
      { name: "Bilal Ahmad", avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Hina Khan",   avatar: "https://i.pravatar.cc/150?img=17" },
    ],
    category: "Completed",
    description:
      "Annual student council election process including nomination collection, campaigning period, voting day, and results announcement. Full democratic process managed by school administration.",
    date: { start: "2025-01-10", end: "2025-01-25" },
    status: "Completed",
    isStarred: true,
    createdAt: "2024-12-20",
    updatedAt: "2025-01-26",
  },
  {
    id: 15,
    projectId: "PRJ-000015",
    name: "Debate Championship",
    code: "DEBC",
    coverImage: "https://picsum.photos/seed/DebateChampionship/400/200",
    adminUser: { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    users: [
      { name: "Ayesha Siddiqui", avatar: "https://i.pravatar.cc/150?img=15" },
      { name: "Omar Farooq",     avatar: "https://i.pravatar.cc/150?img=14" },
      { name: "Zain Ul Abidin",  avatar: "https://i.pravatar.cc/150?img=12" },
    ],
    category: "Active",
    description:
      "Inter-school debate competition on current affairs and social issues. Teams of two students each. Preliminary rounds at school level, winners proceed to district competition.",
    date: { start: "2025-03-10", end: "2025-03-25" },
    status: "Active",
    isStarred: false,
    createdAt: "2025-02-01",
    updatedAt: "2025-02-24",
  },
  {
    id: 16,
    projectId: "PRJ-000016",
    name: "Alumni Reunion",
    code: "ALUM",
    coverImage: "https://picsum.photos/seed/AlumniReunion/400/200",
    adminUser: { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4" },
    users: [
      { name: "Ahmed Khan",  avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Nadia Iqbal", avatar: "https://i.pravatar.cc/150?img=5" },
    ],
    category: "Associate",
    description:
      "Annual alumni meet-up event bringing together graduates from all batches. Programme includes cultural performances, networking sessions, and a gala dinner with the school principal.",
    date: { start: "2025-12-15", end: "2025-12-15" },
    status: "Associate",
    isStarred: false,
    createdAt: "2025-02-25",
    updatedAt: "2025-02-28",
  },
];

export default PROJECTS_DUMMY_DATA;
