const FORMS_DUMMY_DATA = [
  {
    id: 1,
    formId: "FRM-000038",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Chief Executive Officer (CEO)",
    title: "Student Feedback Form",
    description: "Collect feedback from students about their learning experience and classroom environment.",
    privacy: "Public",
    approvers: [
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2", role: "Mathematics Teacher", response: "Approved"   },
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3", role: "Science Teacher",     response: "Approved"   },
    ],
    observers: [
      { name: "Ahmed Khan",    avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5" },
    ],
    status: "Approved",
    isApproved: true,
    questions: [
      { id: 1, questionText: "How would you rate your overall learning experience?", type: "Multiple Choice", required: true,  options: ["Excellent", "Good", "Average", "Poor"] },
      { id: 2, questionText: "What subject do you find most challenging?",            type: "Text",            required: false, options: [] },
      { id: 3, questionText: "Would you recommend this school to others?",            type: "Multiple Choice", required: true,  options: ["Yes", "No", "Maybe"] },
    ],
    createDate: "2025-01-10",
    updateDate: "2025-02-15",
    timeAgo: "2 months ago",
  },
  {
    id: 2,
    formId: "FRM-000037",
    creatorName: "Tariq Mahmood",
    creatorAvatar: "https://i.pravatar.cc/150?img=6",
    creatorRole: "Administrator",
    title: "Parent Satisfaction Survey",
    description: "Annual survey to measure parent satisfaction with school performance and communication.",
    privacy: "Private",
    approvers: [
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4", role: "Chief Executive Officer (CEO)", response: "Approved" },
    ],
    observers: [
      { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    ],
    status: "Approved",
    isApproved: true,
    questions: [
      { id: 1, questionText: "How satisfied are you with the school's communication?", type: "Multiple Choice", required: true,  options: ["Very Satisfied", "Satisfied", "Neutral", "Dissatisfied"] },
      { id: 2, questionText: "Please share any specific concerns or suggestions.",      type: "Text",            required: false, options: [] },
    ],
    createDate: "2025-01-15",
    updateDate: "2025-02-20",
    timeAgo: "6 weeks ago",
  },
  {
    id: 3,
    formId: "FRM-000036",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Chief Executive Officer (CEO)",
    title: "Teacher Evaluation Form",
    description: "Annual performance evaluation form for teaching staff covering classroom management and delivery.",
    privacy: "Private",
    approvers: [
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3", role: "Science Teacher",    response: "InProcess" },
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5", role: "Administrator",      response: "InProcess" },
    ],
    observers: [],
    status: "In Process",
    isApproved: false,
    questions: [
      { id: 1, questionText: "Rate the teacher's subject knowledge.",       type: "Multiple Choice", required: true,  options: ["Excellent", "Good", "Average", "Poor"] },
      { id: 2, questionText: "Rate classroom management skills.",           type: "Multiple Choice", required: true,  options: ["Excellent", "Good", "Average", "Poor"] },
      { id: 3, questionText: "Additional comments about the teacher.",      type: "Text",            required: false, options: [] },
    ],
    createDate: "2025-01-20",
    updateDate: "2025-02-22",
    timeAgo: "5 weeks ago",
  },
  {
    id: 4,
    formId: "FRM-000035",
    creatorName: "Fatima Malik",
    creatorAvatar: "https://i.pravatar.cc/150?img=2",
    creatorRole: "Mathematics Teacher",
    title: "Library Book Request",
    description: "Request form for students to suggest new books to be added to the school library collection.",
    privacy: "Public",
    approvers: [
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4", role: "Chief Executive Officer (CEO)", response: "Approved" },
    ],
    observers: [
      { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    status: "Approved",
    isApproved: true,
    questions: [
      { id: 1, questionText: "What is the title of the book you are requesting?", type: "Text", required: true,  options: [] },
      { id: 2, questionText: "Author name (if known).",                           type: "Text", required: false, options: [] },
      { id: 3, questionText: "Why should this book be added to the library?",     type: "Text", required: true,  options: [] },
    ],
    createDate: "2024-12-05",
    updateDate: "2025-01-10",
    timeAgo: "2 months ago",
  },
  {
    id: 5,
    formId: "FRM-000034",
    creatorName: "Ahmed Khan",
    creatorAvatar: "https://i.pravatar.cc/150?img=1",
    creatorRole: "Science Teacher",
    title: "Sports Team Registration",
    description: "Registration form for students wishing to join school sports teams for the upcoming season.",
    privacy: "Public",
    approvers: [
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2", role: "Mathematics Teacher", response: "Approved"   },
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4", role: "Chief Executive Officer (CEO)", response: "Approved" },
    ],
    observers: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6" },
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5" },
    ],
    status: "Approved",
    isApproved: true,
    questions: [
      { id: 1, questionText: "Which sport are you registering for?",       type: "Multiple Choice", required: true,  options: ["Cricket", "Football", "Basketball", "Badminton", "Swimming"] },
      { id: 2, questionText: "Have you played at inter-school level?",     type: "Multiple Choice", required: true,  options: ["Yes", "No"] },
      { id: 3, questionText: "Any medical conditions we should know of?",  type: "Text",            required: false, options: [] },
    ],
    createDate: "2025-01-25",
    updateDate: "2025-02-05",
    timeAgo: "4 weeks ago",
  },
  {
    id: 6,
    formId: "FRM-000033",
    creatorName: "Nadia Iqbal",
    creatorAvatar: "https://i.pravatar.cc/150?img=5",
    creatorRole: "Administrator",
    title: "Science Fair Registration",
    description: "Registration form for students participating in the annual science fair project competition.",
    privacy: "Public",
    approvers: [
      { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1", role: "Science Teacher", response: "InProcess" },
    ],
    observers: [
      { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    ],
    status: "In Process",
    isApproved: false,
    questions: [
      { id: 1, questionText: "What is your project title?",           type: "Text",            required: true,  options: [] },
      { id: 2, questionText: "What subject area does it fall under?", type: "Multiple Choice", required: true,  options: ["Biology", "Chemistry", "Physics", "Environmental", "Computer Science"] },
      { id: 3, questionText: "Will you work alone or in a group?",    type: "Multiple Choice", required: true,  options: ["Individual", "Pair", "Group of 3"] },
    ],
    createDate: "2025-02-01",
    updateDate: "2025-02-18",
    timeAgo: "2 weeks ago",
  },
  {
    id: 7,
    formId: "FRM-000032",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Chief Executive Officer (CEO)",
    title: "Field Trip Permission",
    description: "Parental consent form required for student participation in off-campus educational field trips.",
    privacy: "Public",
    approvers: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6", role: "Administrator", response: "Approved" },
    ],
    observers: [
      { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    ],
    status: "Approved",
    isApproved: true,
    questions: [
      { id: 1, questionText: "Do you give permission for your child to attend?",       type: "Multiple Choice", required: true,  options: ["Yes, I give permission", "No, I do not give permission"] },
      { id: 2, questionText: "Emergency contact number during the trip.",              type: "Text",            required: true,  options: [] },
      { id: 3, questionText: "Does your child have any dietary restrictions?",         type: "Text",            required: false, options: [] },
      { id: 4, questionText: "Any medical conditions the teacher should be aware of?", type: "Text",            required: false, options: [] },
    ],
    createDate: "2025-02-05",
    updateDate: "2025-02-25",
    timeAgo: "1 week ago",
  },
  {
    id: 8,
    formId: "FRM-000031",
    creatorName: "Fatima Malik",
    creatorAvatar: "https://i.pravatar.cc/150?img=2",
    creatorRole: "Mathematics Teacher",
    title: "Scholarship Application",
    description: "Application form for students seeking merit-based or need-based financial scholarships.",
    privacy: "Private",
    approvers: [
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4", role: "Chief Executive Officer (CEO)", response: "InProcess" },
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5", role: "Administrator",                 response: "InProcess" },
    ],
    observers: [],
    status: "In Process",
    isApproved: false,
    questions: [
      { id: 1, questionText: "What type of scholarship are you applying for?",  type: "Multiple Choice", required: true,  options: ["Merit-Based", "Need-Based", "Sports Excellence", "Arts & Culture"] },
      { id: 2, questionText: "Current academic percentage/GPA.",                 type: "Text",            required: true,  options: [] },
      { id: 3, questionText: "Write a brief statement of purpose (100 words).", type: "Text",            required: true,  options: [] },
    ],
    createDate: "2025-01-30",
    updateDate: "2025-02-10",
    timeAgo: "3 weeks ago",
  },
  {
    id: 9,
    formId: "FRM-000030",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Chief Executive Officer (CEO)",
    title: "Complaint Form",
    description: "Official form for submitting academic or behavioral complaints to school management.",
    privacy: "Private",
    approvers: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6", role: "Administrator", response: "Approved"  },
    ],
    observers: [
      { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    status: "Approved",
    isApproved: true,
    questions: [
      { id: 1, questionText: "Nature of complaint.",         type: "Multiple Choice", required: true,  options: ["Academic", "Behavioral", "Facilities", "Staff Conduct", "Other"] },
      { id: 2, questionText: "Describe the complaint.",     type: "Text",            required: true,  options: [] },
      { id: 3, questionText: "Date of incident.",           type: "Date",            required: true,  options: [] },
      { id: 4, questionText: "Desired resolution outcome.", type: "Text",            required: false, options: [] },
    ],
    createDate: "2024-11-15",
    updateDate: "2024-12-20",
    timeAgo: "3 months ago",
  },
  {
    id: 10,
    formId: "FRM-000029",
    creatorName: "Ahmed Khan",
    creatorAvatar: "https://i.pravatar.cc/150?img=1",
    creatorRole: "Science Teacher",
    title: "Leave Application Form",
    description: "Formal leave application form for teaching and administrative staff requesting planned absence.",
    privacy: "Private",
    approvers: [
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4", role: "Chief Executive Officer (CEO)", response: "Declined" },
    ],
    observers: [],
    status: "Declined",
    isApproved: false,
    questions: [
      { id: 1, questionText: "Type of leave requested.",   type: "Multiple Choice", required: true,  options: ["Sick Leave", "Annual Leave", "Casual Leave", "Maternity Leave", "Other"] },
      { id: 2, questionText: "Start date of leave.",       type: "Date",            required: true,  options: [] },
      { id: 3, questionText: "End date of leave.",         type: "Date",            required: true,  options: [] },
      { id: 4, questionText: "Reason for leave request.",  type: "Text",            required: true,  options: [] },
    ],
    createDate: "2025-01-05",
    updateDate: "2025-01-28",
    timeAgo: "5 weeks ago",
  },
  {
    id: 11,
    formId: "FRM-000028",
    creatorName: "Nadia Iqbal",
    creatorAvatar: "https://i.pravatar.cc/150?img=5",
    creatorRole: "Administrator",
    title: "Club Membership Form",
    description: "Registration form for students applying to join any of the school's extracurricular clubs.",
    privacy: "Public",
    approvers: [
      { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2", role: "Mathematics Teacher", response: "Approved" },
    ],
    observers: [
      { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    ],
    status: "For Review",
    isApproved: false,
    questions: [
      { id: 1, questionText: "Which club are you applying to join?",          type: "Multiple Choice", required: true,  options: ["Science Club", "Drama Club", "Coding Club", "Debate Society", "Art Club"] },
      { id: 2, questionText: "Why do you want to join this club?",            type: "Text",            required: true,  options: [] },
      { id: 3, questionText: "Do you have prior experience in this area?",   type: "Multiple Choice", required: false, options: ["Yes", "No"] },
    ],
    createDate: "2025-02-08",
    updateDate: "2025-02-26",
    timeAgo: "5 days ago",
  },
  {
    id: 12,
    formId: "FRM-000027",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Chief Executive Officer (CEO)",
    title: "Exam Invigilation Request",
    description: "Request form for teachers to volunteer or be assigned exam invigilation duties.",
    privacy: "Private",
    approvers: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6", role: "Administrator",      response: "InProcess" },
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3", role: "Science Teacher",    response: "Approved"  },
    ],
    observers: [],
    status: "In Process",
    isApproved: false,
    questions: [
      { id: 1, questionText: "Which exam session are you available for?",  type: "Checkbox",        required: true,  options: ["Morning (8AM–12PM)", "Afternoon (1PM–5PM)", "Full Day"] },
      { id: 2, questionText: "Any exam dates you cannot cover?",           type: "Text",            required: false, options: [] },
    ],
    createDate: "2025-02-12",
    updateDate: "2025-02-28",
    timeAgo: "3 days ago",
  },
  {
    id: 13,
    formId: "FRM-000026",
    creatorName: "Fatima Malik",
    creatorAvatar: "https://i.pravatar.cc/150?img=2",
    creatorRole: "Mathematics Teacher",
    title: "Approver Checker Test 3",
    description: "Test form to verify multi-level approver workflow and notification routing.",
    privacy: "Private",
    approvers: [
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4", role: "Chief Executive Officer (CEO)", response: "Approved"  },
      { name: "Ahmed Khan",    avatar: "https://i.pravatar.cc/150?img=1", role: "Science Teacher",               response: "InProcess" },
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5", role: "Administrator",                 response: "InProcess" },
    ],
    observers: [
      { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    status: "In Process",
    isApproved: false,
    questions: [
      { id: 1, questionText: "Test question A", type: "Text", required: true,  options: [] },
      { id: 2, questionText: "Test question B", type: "Text", required: false, options: [] },
    ],
    createDate: "2025-02-14",
    updateDate: "2025-02-27",
    timeAgo: "4 days ago",
  },
  {
    id: 14,
    formId: "FRM-000025",
    creatorName: "Ahmed Khan",
    creatorAvatar: "https://i.pravatar.cc/150?img=1",
    creatorRole: "Science Teacher",
    title: "Approver Checker 2",
    description: "Second test form for validating the approver checker pipeline and response states.",
    privacy: "Public",
    approvers: [
      { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2", role: "Mathematics Teacher", response: "Declined" },
    ],
    observers: [],
    status: "Declined",
    isApproved: false,
    questions: [
      { id: 1, questionText: "Test question", type: "Text", required: true, options: [] },
    ],
    createDate: "2025-02-10",
    updateDate: "2025-02-20",
    timeAgo: "10 days ago",
  },
  {
    id: 15,
    formId: "FRM-000024",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Chief Executive Officer (CEO)",
    title: "iOS Dev Test Form",
    description: "Internal form used by the development team to test form rendering on iOS devices.",
    privacy: "Private",
    approvers: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6", role: "Administrator", response: "Approved" },
    ],
    observers: [],
    status: "For Review",
    isApproved: false,
    questions: [
      { id: 1, questionText: "Does the form render correctly on iPhone?",  type: "Multiple Choice", required: true,  options: ["Yes", "No", "Partially"] },
      { id: 2, questionText: "List any rendering issues observed.",        type: "Text",            required: false, options: [] },
    ],
    createDate: "2025-02-16",
    updateDate: "2025-02-28",
    timeAgo: "2 days ago",
  },
  {
    id: 16,
    formId: "FRM-000023",
    creatorName: "Nadia Iqbal",
    creatorAvatar: "https://i.pravatar.cc/150?img=5",
    creatorRole: "Administrator",
    title: "Delete approver test 1",
    description: "Test form for validating the delete approver functionality in multi-level approval chains.",
    privacy: "Private",
    approvers: [
      { name: "Hassan Raza", avatar: "https://i.pravatar.cc/150?img=3", role: "Science Teacher", response: "InProcess" },
    ],
    observers: [],
    status: "In Process",
    isApproved: false,
    questions: [
      { id: 1, questionText: "Sample question for approver delete test.", type: "Text", required: true, options: [] },
    ],
    createDate: "2025-02-18",
    updateDate: "2025-02-28",
    timeAgo: "2 days ago",
  },
  {
    id: 17,
    formId: "FRM-000022",
    creatorName: "Fatima Malik",
    creatorAvatar: "https://i.pravatar.cc/150?img=2",
    creatorRole: "Mathematics Teacher",
    title: "for approval",
    description: "Draft form submitted for initial approval review before going live.",
    privacy: "Public",
    approvers: [
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4", role: "Chief Executive Officer (CEO)", response: "InProcess" },
    ],
    observers: [
      { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    ],
    status: "In Process",
    isApproved: false,
    questions: [
      { id: 1, questionText: "Placeholder question.", type: "Text", required: true, options: [] },
    ],
    createDate: "2025-02-20",
    updateDate: "2025-02-28",
    timeAgo: "today",
  },
  {
    id: 18,
    formId: "FRM-000021",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Chief Executive Officer (CEO)",
    title: "Staff Performance Review",
    description: "Annual staff performance review form for administrative and teaching staff assessment.",
    privacy: "Private",
    approvers: [
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6", role: "Administrator",      response: "Approved"  },
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5", role: "Administrator",      response: "Approved"  },
    ],
    observers: [
      { name: "Fatima Malik", avatar: "https://i.pravatar.cc/150?img=2" },
    ],
    status: "Approved",
    isApproved: true,
    questions: [
      { id: 1, questionText: "Rate your performance this year (1–10).",         type: "Multiple Choice", required: true,  options: ["1–3", "4–6", "7–8", "9–10"] },
      { id: 2, questionText: "Key achievements this academic year.",             type: "Text",            required: true,  options: [] },
      { id: 3, questionText: "Professional development goals for next year.",    type: "Text",            required: true,  options: [] },
      { id: 4, questionText: "Any challenges that impacted your performance?",   type: "Text",            required: false, options: [] },
    ],
    createDate: "2024-12-01",
    updateDate: "2025-01-05",
    timeAgo: "2 months ago",
  },
  {
    id: 19,
    formId: "FRM-000020",
    creatorName: "Ahmed Khan",
    creatorAvatar: "https://i.pravatar.cc/150?img=1",
    creatorRole: "Science Teacher",
    title: "New Student Registration",
    description: "Registration form for new students enrolling in the school for the upcoming academic year.",
    privacy: "Public",
    approvers: [
      { name: "Administrator", avatar: "https://i.pravatar.cc/150?img=4", role: "Chief Executive Officer (CEO)", response: "Approved" },
    ],
    observers: [
      { name: "Nadia Iqbal",   avatar: "https://i.pravatar.cc/150?img=5" },
      { name: "Hassan Raza",   avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    status: "Approved",
    isApproved: true,
    questions: [
      { id: 1, questionText: "Full name of student.",       type: "Text",            required: true,  options: [] },
      { id: 2, questionText: "Date of birth.",              type: "Date",            required: true,  options: [] },
      { id: 3, questionText: "Grade applying for.",         type: "Multiple Choice", required: true,  options: ["Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11"] },
      { id: 4, questionText: "Previous school attended.",   type: "Text",            required: false, options: [] },
    ],
    createDate: "2024-11-01",
    updateDate: "2024-12-15",
    timeAgo: "3 months ago",
  },
  {
    id: 20,
    formId: "FRM-000019",
    creatorName: "Administrator",
    creatorAvatar: "https://i.pravatar.cc/150?img=4",
    creatorRole: "Chief Executive Officer (CEO)",
    title: "Annual Report Feedback",
    description: "Feedback form for stakeholders to comment on the school's annual academic and financial report.",
    privacy: "Public",
    approvers: [
      { name: "Fatima Malik",  avatar: "https://i.pravatar.cc/150?img=2", role: "Mathematics Teacher", response: "Approved" },
      { name: "Tariq Mahmood", avatar: "https://i.pravatar.cc/150?img=6", role: "Administrator",       response: "Approved" },
    ],
    observers: [
      { name: "Ahmed Khan", avatar: "https://i.pravatar.cc/150?img=1" },
    ],
    status: "For Review",
    isApproved: false,
    questions: [
      { id: 1, questionText: "How would you rate the annual report presentation?",  type: "Multiple Choice", required: true,  options: ["Excellent", "Good", "Needs Improvement"] },
      { id: 2, questionText: "What sections need more detail?",                     type: "Checkbox",        required: false, options: ["Academic Performance", "Financial Summary", "Future Plans", "Infrastructure"] },
      { id: 3, questionText: "Any additional comments or suggestions.",             type: "Text",            required: false, options: [] },
    ],
    createDate: "2025-02-15",
    updateDate: "2025-02-28",
    timeAgo: "2 days ago",
  },
];

export default FORMS_DUMMY_DATA;
