const classes = [
  {
    id: "CLS001",
    name: "Class X-A",
    level: "10",
    section: "A",
    classTeacher: "Mr. Robert Smith",
    studentCount: 42,
    totalStrength: 45,
    classroom: "Block-B, Room 201",
    timings: "08:00 AM - 2:00 PM",
    startDate: "01 Aug 2024",
    endDate: "31 May 2025",
    status: "Active",
    averageAttendance: 92,
    performance: 85,
  },
  {
    id: "CLS002",
    name: "Class X-B",
    level: "10",
    section: "B",
    classTeacher: "Ms. Emily Johnson",
    studentCount: 40,
    totalStrength: 45,
    classroom: "Block-B, Room 202",
    timings: "08:00 AM - 2:00 PM",
    startDate: "01 Aug 2024",
    endDate: "31 May 2025",
    status: "Active",
    averageAttendance: 88,
    performance: 82,
  },
  {
    id: "CLS003",
    name: "Class X-C",
    level: "10",
    section: "C",
    classTeacher: "Dr. Michael Brown",
    studentCount: 39,
    totalStrength: 45,
    classroom: "Block-C, Room 301",
    timings: "08:00 AM - 2:00 PM",
    startDate: "01 Aug 2024",
    endDate: "31 May 2025",
    status: "Active",
    averageAttendance: 90,
    performance: 88,
  },
  {
    id: "CLS004",
    name: "Class IX-A",
    level: "9",
    section: "A",
    classTeacher: "Ms. Sarah Williams",
    studentCount: 43,
    totalStrength: 45,
    classroom: "Block-A, Room 101",
    timings: "08:00 AM - 2:00 PM",
    startDate: "01 Aug 2024",
    endDate: "31 May 2025",
    status: "Active",
    averageAttendance: 91,
    performance: 84,
  },
  {
    id: "CLS005",
    name: "Class IX-B",
    level: "9",
    section: "B",
    classTeacher: "Prof. David Miller",
    studentCount: 41,
    totalStrength: 45,
    classroom: "Block-A, Room 102",
    timings: "08:00 AM - 2:00 PM",
    startDate: "01 Aug 2024",
    endDate: "31 May 2025",
    status: "Active",
    averageAttendance: 87,
    performance: 80,
  },
  {
    id: "CLS006",
    name: "Class VIII-A",
    level: "8",
    section: "A",
    classTeacher: "Mrs. Lisa Anderson",
    studentCount: 44,
    totalStrength: 45,
    classroom: "Block-A, Room 201",
    timings: "08:00 AM - 2:00 PM",
    startDate: "01 Aug 2024",
    endDate: "31 May 2025",
    status: "Active",
    averageAttendance: 93,
    performance: 86,
  },
  {
    id: "CLS007",
    name: "Class VIII-B",
    level: "8",
    section: "B",
    classTeacher: "Mr. James Wilson",
    studentCount: 42,
    totalStrength: 45,
    classroom: "Block-A, Room 202",
    timings: "08:00 AM - 2:00 PM",
    startDate: "01 Aug 2024",
    endDate: "31 May 2025",
    status: "Active",
    averageAttendance: 89,
    performance: 83,
  },
  {
    id: "CLS008",
    name: "Class VII-A",
    level: "7",
    section: "A",
    classTeacher: "Ms. Jennifer Davis",
    studentCount: 45,
    totalStrength: 45,
    classroom: "Block-C, Room 101",
    timings: "08:00 AM - 2:00 PM",
    startDate: "01 Aug 2024",
    endDate: "31 May 2025",
    status: "Active",
    averageAttendance: 94,
    performance: 87,
  },
];

export default classes;
